### ISSUE TITLE
Controller_Template->template - what is the datatype?

### ISSUE THREAD

**Issue by consilience** [fuel/core#1000]
I was looking at setting the name of the page wrapper template in a controller method, as one or two methods needed a different output format. This led to an error when setting $this->template in the controller.

Looking at the controller classes, the $template property starts as a string - the name of the template. At some point it magically turns into an object. The magic happens on this line:

$this->template = \View::forge($this->template);

i.e. set the string to be an object, based on the string that the object started off as. 

My FR is to not change datatypes like this, as it leads to much confusion further down the line. Perhaps put the template name in the $template_name property.

Functionally it works as it is, but it is storing up trouble for later.

**Comment by consilience** [comment]
Just to add to this, because the template _name_ was converted into a template _object_ in the before() method of the Controller_Template class, before calls up subsequent initialisation methods, it means that there is no opportunity for the controller method to set that template dynamically.

A controller method can run $this->template = \View::forge('template-foobar'), but other code in the before() chain may already have started making assumptions based on what $this->template was (e.g. setting $this->template->title). Maybe swap the order in which actions happen in the Controller_Template::before() method, so that child before() methods run first and can change the name of the template before it is converted into a template object at the end.

Dunno though - perhaps my use-case is the exception. I should probably just split my controller into two controllers, but with the hassle of routing some URLs for the main controller off to the secondary controller (I want them to look like one controller).

See what you think, before I ramble on too much more ;-)

**Comment by WanWizard** [comment]
It is either a View object, or a string containing the name of the view. If it's a string, the base controller will create the View object for you.

If you want dynamic template changes based on the method called, either do it in the before() method before calling the parent::before(), or utilize the router() method (note that it is called after before!).

But if the template really changes for each view, perhaps you should use the template base controller, but just create the View object in your action method, and have it return that.

**Comment by consilience** [comment]
I think this was may main issue:

"It is either a View object, or a string containing the name of the view."

It should be one or the other, and if both are needed, then they should be different properties.

I suspect this is more something that needs to be noted for future versions rather than something that can be changed for FuelPHP 1.x (with the usual arguments/discussions about this kind of approach in the forums).

On changing the template dynamically in before(): does my controller set the property to the name of the template, or set the whole template object? That is a rhetorical question. The point is, it could be either, depending on the order in which the before() functions are chained in the class hierarchy.

**Comment by WanWizard** [comment]
I do not agree with this. 

The goal of the template controller is to provide and easy and highly automated way of generating pages, using a standard template. To this effect, all you have to do is assign the view name to the property. You can only assign scalars to a property, so that's the only choice you have there,

As a string is useless, it needs to be converted to a View object, which the base controllers before() method does.

Alternatively, you may opt to assign your own object. The main reason for this is not that you can assign a View object manually (because that is what the before() method does for you), but to assign something else. Like a Viewmodel for example. Or the result of some method call. Or a closure that returns something suitable.

If you do that before you call parent::before(), nothing will happen, it will see you've already assigned something yourself. If you do it after you call parent::before(), nothing will happen, as it doesn't do anything if no template string was specified in the property. So, location of the call to the parent is not relevant.
