### ISSUE TITLE
Autoloader is partially case sensitive

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#1014]
The auto loader is partially case sensitive and partially case insensitive. All of the string position checks use stripos (this relates to something I spoke with Dan and WanWizard about months back) however the array_key_exists check is case sensitive.

This relates to this line: https://github.com/fuel/core/blob/1.3/develop/classes/autoloader.php#L234

I'd submit a fix however my solution is gross and kills kittens:

``` php
<?php
if (array_key_exists(strtolower($class), array_change_key_case(static::$classes)))
{
    $classes = array_change_key_case(static::$classes);
    include str_replace('/', DS, $classes[strtolower($class)]);
    static::init_class($class);
    $loaded = true;
}
```

**Comment by WanWizard** [comment]
I can find only one stripos() in the autoloader, which is to detect the namespace.

PHP is pretty weird when it comes to case, I would like to propose to change it the other way around, and remove the stripos to make the autoloader fully case sensitive, if only for consistency of your code.

@jschreuder, any comments on this?

**Comment by Propcomm** [comment]
There's a strripos too. PHP isn't weird when it comes to the case of classes or namespaces - it's case insensitive. I wouldn't be a big fan of changing this behaviour at the autoloader level because it makes testing more complex - for example, when a particular line of code using an incorrectly cased namespace/class is called that class may already have been loaded and PHP will use it fine. In another instance, that same line of code may fail because the class has not yet been loaded at that point.

**Comment by phil-lavin** [comment]
Oops. That was me, logged in on the wrong account :S

**Comment by frankdejonge** [comment]
This is adressed in 2.0 where we use PRS style autoload file/dir naming
