### ISSUE TITLE
migrations.php deleted after update to 1.3

### ISSUE THREAD

**Issue by mwager** [fuel/core#1160]
after upgrading to v1.3 each time i run a migration via oil the file `fuel/app/config/migrations.php` gets deleted.

command:
`$ php oil r migrate -all`

as documented [here](http://docs.fuelphp.com/general/migrations.html) one should copy this config file from core to app/config like any other config file

what's wrong? why this file gets deleted ?

**Comment by WanWizard** [comment]
Docs weren't updated, this has been corrected for 1.4.

In 1.3, migrations became environment specific. Since each environment has it's own database config and database tables, having global migrations was a disaster when you started to deploy.

So the file isn't deleted, it's moved to the current config/environment folder the first time you start a migration.
