### ISSUE TITLE
Session::set_flash throws notice after Session::destroy

### ISSUE THREAD

**Issue by tomschlick** [fuel/core#1211]
Ideally it should check for a session and if there is not one create one.

This is the error received. http://snipr.it/~rt

**Comment by WanWizard** [comment]
I've seen it happen once, I can't reproduce it, and I can't find why 'user_agent' would not be present, but all other required session key variables that are tested the same way in the same location appearently are (otherwise they would throw the same notice)?

Can you reproduce this? If so, can you check what the contents of $this->keys is when it happens?
