### ISSUE TITLE
Session dot notation support for set_flash to match get_flash

### ISSUE THREAD

**Issue by dmyers** [fuel/core#1213]
I changed it in mine to test and it worked by changing it to support dot notation like set_flash.

http://snipr.it/~rs

FrenkyNet noted though that it should be tweaked a bit, but I just wanted to show it working.

It would be nice to have in 1.4 branch as I don't want to override core and wait for 1.5 and not sure what to do with my app as it also would be worse to go back to 1.3 as I want to use 1.4 features. :D

**Comment by WanWizard** [comment]
It's not this easy, otherwise it would have been already implemented.

The problem is that flash data is, as you noticed, stored as a datastructure, with metadata besides the actual flash data.

Consider this scenario:

``` php
Session::set_flash('test', array('a' => 'value'));
Session::set_flash('test.a', 'other-value');
$flash = Session::get_flash('test');
```

Now $flash contains not only the data, but also the metadata inserted by the second call to set_flash().

It gets worse. Consider if you would do a keep_flash('test.a'). It would not be kept, since it's parent would still be expired and therefore erased before updating the session store.

**Comment by dmyers** [comment]
Closing as it looks 02461e1e22759577f2c97d44e3d9857aa7fc9137 fixes this. Thanks Wan.

**Comment by WanWizard** [comment]
Doesn't really fix it, but it's a start. But it fixes the problem of the metadata at sublevels...
