### ISSUE TITLE
Invalid email/url validation for utf8

### ISSUE THREAD

**Issue by oaass** [fuel/core#1233]
filter_var() alone does not validate emails and domains containing utf8. For example a URL like www.øl.no is a valid and existing (though suspended by host) domain. filter_var() returns that as false.

Look into idn_*() (http://www.php.net/idn_to_ascii). This will make sure all domains validate properly. Like www.øl.no will be converted to www.xn--l-4ga.no which will validate correctly

**Comment by WanWizard** [comment]
This would require the presence of a PECL extension, which is a dependency we would like to avoid.

**Comment by WanWizard** [comment]
I've been looking and asking around, and consensus seems to be that with the introduction of utf-8 in emails, and all kinds of custom tld's, it virtually pointless to validate an email address above a format like "<something>@<something>.<something>". It's impossible to come up with a regex that is free of both false positives and false negatives.

Since your proposed solution requires PECL, we won't include that in the core. I would suggest you implement your own validation extension in which you overload the valid_email method, to fix your problem.
