### ISSUE TITLE
Default language, request, before & routing issue

### ISSUE THREAD

**Issue by rob-bar** [fuel/core#1247]
Hi all,

We recently came out to this very interesting issue with the version 1.4 of the core.
Wa allready nailed the issue down in the core, but either way this is a serious issue or this is a misimplementation of us.
Please point out the right approach if we are doing it wrong.

SO:
our code in the home template_controller

``` php
  public function before(){
    parent::before();
    Config::set('language', $this->param('lang'));
    Lang::load('site.yml');
  }

  public function action_index() {
    var_dump(Config::get('language'));
    var_dump($this->param('lang'));
    var_dump(__('messagedata.title'));
    exit;
  }
```

route in routes.php:
':lang/home'    =>  '/home',

this shows:
**string(2) "fr" string(2) "fr" string(23) "Copy title fr"**
when we visit our.domain/fr/home

&

**string(2) "nl" string(2) "nl" string(23) "Copy title nl"**
when we visit our.domain/nl/home

so everything here is ok....

HOWEVER!

when we visit our.domain/fr/home
for example and
when we add in a:

``` php
$this->template->set_global('lang', $this->param('lang'));
```

in the before like so:

``` php
  public function before(){
    parent::before();
    Config::set('language', $this->param('lang'));
    Lang::load('site.yml');
    $this->template->set_global('lang', $this->param('lang'));
  }
```

and we trace out this:

``` php
<?php
    var_dump($lang);
    var_dump(Config::get('language'));
    var_dump(__('messagedata.title'));
    exit;
?>
```

 in one of the partials or in the template itself in the views folder we get some strange things.
This is the output:
**string(2) "fr" string(2) "nl" NULL**
So what happened?
Well the config language is the problem.

In line 358 & 437 in the request class in the core the language is put in a var which is restored in the config after a chunk of code....
If we comment out the line 437 we get as output in the view
*_string(2) "nl" string(23) "Copy title nl van :name" *_

AS EXPECTED. 

Also you guys really want to avoid lines like this in the core request class:

``` php
                // save the current language so we can restore it after the call
line 358        $current_language = \Config::get('language', 'en');
line 358 suggestion     $current_language = \Config::get('language', \Config::get('language_fallback'));
```

like the suggestion its more dynamic

Thanks for your reply and sorry for the long explenation....:)
cheers

**Comment by WanWizard** [comment]
The language is initially set in your config file. This is the global language that FuelPHP will use if nothing else is set.

However, "language" is a request property. Per request, you can change the language as much as you want, when the request is finished, the request-local language will be reset in order to avoid "leaking" into the next request. This is only relevant in an HMVC context, where you have multiple internal requests per client request.

I have a feeling that you have this issue because in the global config, the language is not set (or set to blank). That is not a supported setup, it should contain a valid language.

**Comment by rob-bar** [comment]
our config looks like this.

``` php
    /**
     * Localization & internationalization settings
     */
    'language'           => 'nl', // Default language
    'language_fallback'  => '', // Fallback language when file isn't available for default language
    'locale'             => 'nl_BE', // PHP set_locale() setting, null to not set

    'encoding'  => 'UTF-8',
```

We had to leave out the fallback language because when we leave that in the keys form the default language get put in the array of Lang::load()

**Comment by rob-bar** [comment]
see https://github.com/fuel/core/issues/1183

**Comment by WanWizard** [comment]
That still doesn't explain why you have this issue.

When the framework loads, the language is set to 'nl' as per your config. The Request starts, which caches the current language set, and starts loading the controller. It gets only restored after the request is completely handled.

You don't specify it, but I now start to think that the snippet where you dump the values is actually in your view file?

If so, then that's were you go wrong. Views by default are lazy rendered (read the docs on what that means), so by the time that code is executed, the request has since long finished, and the language set inside the request lost.

Your View files should not contain code, other then simple structures to layout your page.

**Comment by rob-bar** [comment]
Yeah exactly, that is in my view files.
Ok I'll look into this lazy loading of the views.

## I'll respond as quickly as possible.

Robbie Bardijn
Front-end Developer

Mobile: 0472 / 79.88.63
robbie.bardijn@gmail.com

**Comment by WanWizard** [comment]
@rob-bar any update on this?

**Comment by rob-bar** [comment]
Sorry for my late response...I'll look into it today.That you can close this issue or not

**Comment by rob-bar** [comment]
Ok I looked into tis and force rendered the views. 
Still no luck.
What are your suggestions?
The thing we wanted to do was directly call the `__('key to lang string')` function so that we could directly print out values from our yml files in the lang folder (thus language based)  in our view files...
like so:

```
<div id="mid">
    <h2><?= __("home.h2"); ?></h2>
    <h3><?= __("home.h3"); ?></h3>
    <p><?= __("home.p"); ?></p>
    <a href="#" class="btn"><?= __("home.cta"); ?> <span></span></a>
    <br>
    <a href="#"><?= __("home.winners"); ?></a>
</div>
```

**Comment by rob-bar** [comment]
We had no issues when we did this with version 1.3
Here's the commit on the request file
https://github.com/fuel/core/commit/5a6ad00cb44eedca74cf47a4a3c48cff1b825a7b

**Comment by WanWizard** [comment]
Correct, the language setting is not a global setting, it's a per-request setting. So that commit is correct, it fixed the bug.

This however exposed the bug that the View class doesn't use the request-context setting, but the global one, which can be different between the moment of creation of the instance, and the moment of rendering.

This has been fixed in 1.5/develop, now the View class will swap languages to the active language at the time the View instance was created before rendering the view.

You can test that by swapping the View class in your 1.4 installation by the one from the 1.5/develop repository.

**Comment by rob-bar** [comment]
Big thanks! 
I will bump up our version to the 1.5 master version and retest this workflow...when I have the spare time
again...thanks!

**Comment by rob-bar** [comment]
This is fixed

**Comment by WanWizard** [comment]
Thanks for the feedback.
