### ISSUE TITLE
Session flash_auto_expire default to false

### ISSUE THREAD

**Issue by ackerdev** [fuel/core#1256]
When `flash_auto_expire` is enabled as it is by default, unexpected behavior can occur if a page asset 404s on the action that set the flash. (I believe the cause is that 404s are being handled by Fuel behind the scenes and causing your flash vars to be auto-expired on the request).

If there is no compelling argument against it, I would suggest that `flash_auto_expire` be set to `true` by default to avoid running into this behavior. With the default of 2hr expiry time of flash vars, I don't believe this would have any large impact in performance or cluttering up Session, and would prevent this elusive error.

**Comment by WanWizard** [comment]
Flash variables should by default expire after the next request. 

If you have an issue because a) your missing an asset and b) you have your rewrite rules so that a missing asset causes a rewrite to index.php, then you have a fault in your application. We will not modify the framework to adapt to that scenario.
