### ISSUE TITLE
Form::input not handling CE chars properly

### ISSUE THREAD

**Issue by Coccodrillo** [fuel/core#126]
Form::input from scaffold edit form displays Central European characters Š and š as &Scaron; and &scaron; regardless of db encoding

```
<?php echo Form::input('keywords', Input::post('keywords', isset($site) ? $site->keywords : '')); ?>
```

however this is ok:

```
input type="text" name="keywords" value="<? echo Input::post('keywords', isset($site) ? $site->keywords : '') ?>"
```

as is the display from var_dump() and all other CE specific signs.

**Comment by jschreuder** [comment]
From this bugreport I have no clue what you're expecting and what you're getting. What output does your first example produce and what's the correct output produced by your second example?

Also indent code by 4 spaces next time, makes for easier reading.

**Comment by Coccodrillo** [comment]
Ah, it displayed the html entities as is should - my bad. Well, when I use form class to create an input or textarea field and set the values, instead of the characters mentioned above (š and Š) their html entity names get displayed  - scaron; and Scaron; (ommiting the ampersand so it doesn't get converted again). In every other case the characters get displayed as they should, so I don't think it's a problem with file encoding and changing the db encoding doesn't seem to make any difference. If i create the input tags manually, everything is displayed as it should be.

**Comment by jschreuder** [comment]
Ahh, the Form class automaticly encodes the values that are passed to it. But in your case this is trouble because your values are already encoded. There's 3 ways to solve this:
1. html_entity_decode() all values before setting them to the form
2. use `Form::set_class_config('prep_value', false)` to disable this encoding in the Form class for all forms/fields
3. set an attribute 'dont_prep' with value `true` on the fields which shouldn't be encoded

I'm closing this issue, reopen if there's something wrong about what I just said.
