### ISSUE TITLE
Session Table Issue

### ISSUE THREAD

**Issue by kenmahn** [fuel/core#1312]
I was not sure where to put the issue since involves both the oil and core systems.

When creating a session table using oil, the program does not take into consideration if a different driver is being used besides mySQL. This process and session code needs to be updated to handle the different databases that will be used.

**Comment by WanWizard** [comment]
The session task uses the DBUtil class, and unfortunately that is very MySQL centric at the moment.

That can only be fixed by moving the DB utility methods into the DB drivers, so they can be made platform specific. This is a change we're not going to do, as v2.0 will use a different DB layer which has already solved this issue.
