### ISSUE TITLE
Misbehaving action_404 on Controller\Rest

### ISSUE THREAD

**Issue by philipptempel** [fuel/core#1424]
Coming from Codeigniter I started using FuelPHP couple of days ago; so bare with me if I did something obviously wrong ;)

I created a controller `base` that `extends \Controller_Rest` and added three methods:
- before()
- after()
- action_404()

adding the _404_ route to `base/404`. Now, what I wanted to achieve: Every request that would throw a HttpNotFoundException should be caught by `base::action_404()`. However, this only works for non-existing controllers but not for methods that don't exist within the current controller. I'm using the Theme-class as well for theming, so maybe this creates a problem.
I don't want to include the whole code here since it's a lot, but you can have a look [on my working repo](https://github.com/hubspace/gasoline/blob/06eb7157f0c3ca44c6b0d79229cdce75161d5dea/fuel/app/classes/controller/base.php#L212:L215) (lines 212:215)

There's also a fix in the method `base::router()` to fix this issue and it works (at least from my point of view and throws proper 404 status codes as well as displays the 404-page I defined in `base::action_404()`.

I'm not saying my workaround is correct, but maybe it is a bug in FuelPHP that should be solved. Otherwise, mark this issue as "invalid" and I'll just keep the code as my workaround in my app ;)

Cheers!

**Comment by Art4** [comment]
I've found this behavior two weeks ago. I'm using the Theme class, modules and the Hybrid Controller. I built a workaroud for this by extending the router method in my Controller_Base. 

I have not reported this because I was not sure, if this is a bug and how to explain this.  :-)

Here is my code:

``` php
    public function router($resource, $arguments)
    {
        // router() von Hybrid_Controller aufrufen
        $response = parent::router($resource, $arguments);

        //Workaround, wenn Methode nicht exisiert
        if ( $this->response->status == 405 )
        {
            $method_name = 'index';

            // If they call user, go to $this->post_user();
            $controller_method = strtolower(\Input::method()) . '_' . $method_name;

            // Fall back to action_ if no rest method is provided
            if ( ! method_exists($this, $controller_method))
            {
                $controller_method = 'action_'.$method_name;
            }

            // If method is not available, set status code to 404
            if (method_exists($this, $controller_method))
            {
                return call_user_func_array(array($this, $controller_method), $arguments);
            }
            else
            {
                throw new \HttpNotFoundException();
            }
        }

        return $response;
    }
```

The method looks for a [method]_index method (i.e. get_index) and for the action_index method and calls them. Otherwise it throws a HttpNotFoundException.

Instead of throwing the HttpNotFoundException() you can call your action_404 method. In my case all Controller extends the Controler_Base. There I can extend the router method, catch the HttpNotFoundException and call another method if needed.

**Comment by philipptempel** [comment]
Glad somebody else ran across this issue, too. However, I'm not quite sure, whether it's a real issue or just something I, or we respectively, haven't understand about how the stuff works.

Your code throwing a `new \HttpNotFoundException()` might be slightly more proper than my approach (since the `HttpNotFoundException` is being caught by the app itself and then returns the `_404_` route, if I understood some other forums discussion correctly).
However, I think there's still some issue related to a method that cannot be found returning the default page (at least using `\Theme` for rendering) and not a designated 404-page.

Maybe someone of the @fuel team can shed some light?!

**Comment by Art4** [comment]
> Your code throwing a new \HttpNotFoundException() might be slightly more proper than my approach (since the HttpNotFoundException is being caught by the app itself and then returns the _404_ route, if I understood some other forums discussion correctly).

Yes, the HttpNotFoundException will be caught in public/index.php and in most case there is no need to catch it inside the Controller.

**Comment by WanWizard** [comment]
You should always throw HttpNotFoundException, so your app behaves consistently, wether it is a a request to a non-existent controller method, or application logic that decides a "not found" is in order.

**Comment by Art4** [comment]
@WanWizard So, Controller_Rest::router() should throw a HttpNotFoundException here? https://github.com/fuel/core/blob/1.7/develop/classes/controller/rest.php#L154:L155

**Comment by frankdejonge** [comment]
@Art4 the status message is correct, REST is modeled around resources, the 405 response generated from this reflects what's expected from REST so we should not move away from that.

**Comment by frankdejonge** [comment]
@philipptempel The controllers in FuelPHP are prefixed with `Controller_` so a class named `base` will never work, so a 404 route to `base/404` will also not work. You could name the class `Controller_Base` which would the be routable and the `base/404` route would work too. Also the 404 route is app global, there are (so far) no controller specific 404 methods. The router method which you're implemented is a good example of why we keep FuelPHP extendible. So I think there's not so much a bug but the behaviour was unexpected in comparison to CodeIgniter. With there comments, does it make things clear? Or do you have other issues/questions? If not, the issue can be closed :)

**Comment by Art4** [comment]
@FrenkyNet I agree, but in my case I've extended the Hybrid Controller.

If I start a not-restful Request (i.e. GET) for a not-existing method in an existing Module like http://example.com/module/notexistingmethod how can I handle this in my controller? Controller_Rest::router() can't found a method, sets $this->response->status to 405 and returns nothing.

The result is an empty page (except the page skeleton from Controller_Base::template), because my Controller had no chance to react or generating some data.

**Comment by frankdejonge** [comment]
@Art4 this requires some rewrite and more logic we can put into a simple fix, I'd suggest for now to extend the route method like this:

``` php
    /**
     * Router
     *
     * Requests are not made to methods directly The request will be for an "object".
     * this simply maps the object and method to the correct Controller method.
     *
     * @param  string
     * @param  array
     */
    public function router($resource, $arguments)
    {
        parent::router($resource, $arguments);

        if ( ! $this->is_restful() and $this->response->status === $this->no_method_status)
        {
            throw new \HttpNotFoundException();
        }
    }
```

**Comment by Art4** [comment]
@FrenkyNet Thank you, this will work for me. :+1:
What about you, @philipptempel?

**Comment by WanWizard** [comment]
@Art4 you have to be careful with REST, by default HTTPNotFoundException is handled in index.php by doing a new request for the 404 route, which by default is not REST-aware. And the last thing you want is to return a bunch of HTML on a REST request.

Also, the way "not found" situations are handled in a REST environment is very application specific, and often dependent on the way the clients are coded. So it's difficult to find a one-solution-fits-all, which is why the core code takes a careful approach in handling these errors, knowing that you can always extend to make it behave like you want.

**Comment by Art4** [comment]
@WanWizard I have written a Controller_Error and set the 404 route to error/404. This Controller is REST-aware and handels the request.

**Comment by WanWizard** [comment]
That would be the way to centrally handle 404 errors, yes.

**Comment by philipptempel** [comment]
Thanks to all participants. Your posts cleared up my mind and also helped me get to know the workings of FuelPHP and RESTful services. I also looked at the code of the Controller_Rest class and I think I now got it all working correctly with a dedicated error-handling class/controller and everything set up for supporting RESTful services.

Thanks a lot again!
