### ISSUE TITLE
Issue with dot in language config key

### ISSUE THREAD

**Issue by jozefKapicak** [fuel/core#145]
Hi,

there is some issue with dots in keys of the language array. 
If there is a dot in the key, it will not show translated / language text:

lang/en.php 

return array(
       'promotion.details.your_offer' => 'Your offer'
)

echo Lang::line('promotion.details.your_offer');  // tis should display 'Your offer', but displays only a dot "."

Regards

Jozef

**Comment by jschreuder** [comment]
This is not an issue. It's because dots are used to get into "group", or actually arrays.

When your language array looks like this:

```
array(
    'key' => 'something',
    'test' => array(
        'deeper' => 'value'
    )
)
```

You can access the values using `Lang::line('key')` and `Lang::line('test.deeper')` it's also possible to put an entire file you load into a subarray. [Read more about that in the docs](http://fuelphp.com/docs/classes/lang.html).
