### ISSUE TITLE
What's best solution of use ViewModel for REST API ?

### ISSUE THREAD

**Issue by takyam-git** [fuel/core#1462]
I offten use ViewModel class for generate views.
But currently ViewModel class can't use for generate data for REST API.

I want to do like this.

``` php
<?php
// fuel/app/classes/controller/foo.php
class Controller_Foo extends Controller_Rest
{
    public function get_bar()
    {
        $this->response(ViewModel::forge('foo/bar')->render());
    }
}

// fuel/app/classes/view/foo/bar.php
class View_Foo_Bar extends ViewModel_Rest
{
    public function view()
    {
        return Model_Bar::find('first', array(
            'where' => array(
                array(
                    'created_at',
                    '>=',
                    date('Y-m-d H:i:s', strtotime('-1 day'))
                )
            )
        ));
    }
}
```

And get response json on access to `http://example.com/foo/bar.json`

Please see my test commit.
https://github.com/takyam-git/core/commit/605aa674b1573d14eb1904fc7deaa0525ead5674

My test commit is not good solution, because `render()` will not render, and have empty dummy view file `views/viemodel/rest.php`.

Do you have a solution?

**Comment by WanWizard** [comment]
A Viewmodel is for abstracting prepping logic from the actual view, they go together, a view file is required for a Viewmodel to work.

You can overload `set_view()` so that it doesn't create a View object, you also need to overload the `render()` method so that it doesn't call `render()` on the View object.

**Comment by takyam-git** [comment]
When overload `set_view()` and doesn't create a View object, I can't call `get()`, `set()` and `isset()` methods, because get/set uses View object

**Comment by WanWizard** [comment]
Thats the downside of not having a View object. A Viewmodel is designed to augment the View, you're trying to make it do something it wasn't designed to.

**Comment by takyam-git** [comment]
I understand that ViewModel is not good for Controller_Rest, and I want class which contains business logic for controller will not be fat.
But I want to use that class, like a ViewModel ( get()/set()/before() ).
- my want
  - Create new class that contains business logic,  per actions, like a ViewModel for Controller_Rest.
  - The class can response, like a `$this->response()` in Controller_Rest.

If there's no solution for my want, I'll create that class for me.

**Comment by WanWizard** [comment]
In your Viewmodel class, you can set the _view property to an empty view file. You can then use the created View object as a data container for your set/get/isset.

Then overload the render() method, and have it return the json structure instead of calling render() on the View object.

If you need this more then once, create a Viewmodel base class that does this, and have your Viewmodels extend this base class.

**Comment by takyam-git** [comment]
Thank you, I'll create it in app/classes. It's looks like not good solution(method name, empty view), but it's easy way for my needs.
