### ISSUE TITLE
Database Storage for Config Class

### ISSUE THREAD

**Issue by iamacarpet** [fuel/core#1533]
Hello,

We're having some problems in our implementation of a site written in the framework when moving it to a new platform with high availability web servers.

The current way of storing the config files as text based arrays (php,json,etc) on the file-system is causing us problems with replication, in the sense that we'd have to use rsync to keep all the nodes up-to-date and we could only run the scripts that make changes to those config files on one node to make that the master, eliminating a part of our high availability.

We've had a long discussion in-house and decided the best way to go about this would be to store the values in a database - this may involve a lot of selects rather than disk reads, but in our environment our database access is a lot less expensive than disk access.

Just to float the question out there, we were debating if we should extend the class ourselves just as part of our app, or would anyone find it beneficial if we fork, edit the Config class and submit the changes?

Does anyone have any comments?

Regards,
iamacarpet

**Comment by emlynwest** [comment]
Just given the config code a quick look and it appears to be driver based. The config interface provides a `load` (select from DB) and a `save` (insert/update) method. Potentially you will be able to create the new driver and transparently load from your DB instead of reading from file.

I could be wrong however but that seems to be how it works on the surface. Failing that you can easily extend the config class in your app to provide the functionality you desire.

**Comment by WanWizard** [comment]
The problem with this is that you need Config long before you have access to the DB, and (obviously) you need Config also to read and process the 'db.php' config file. You would also need a config configuration, to tell the driver which table to use, etc. This also needs to be loaded before a DB driver could work. This complexity is the reason it's not implemented at the moment.

Since config data is stored internally in a single multidimensional array, it would be a lot simpler just to have a bit of startup code that loads config data from the DB, and merge the fetched data into Config::$items.

**Comment by iamacarpet** [comment]
@WanWizard Thanks for the input. We implemented it with a very simple driver and table structure that basically expands on the existing JSON driver.

https://gist.github.com/iamacarpet/6869643

For our use-case, the configuration that needs to be shared between nodes via the database is just dynamically generated configuration that is changed and saved in the code. Any other configuration, including the config to connect to the database initially, should be checked in to our repository and so replicated via our deployment path.

Also, because we wanted to keep it simple, the driver is used by adding it to your autoload section of bootstrap.php - and then when opening / saving configuration using the Config class - just use it as you normally would with file, but append the .db extension to the end to call the database driver.

We haven't yet found any shortcomings in our application, but we may not be using the Config class to its full potential. I would greatly appreciate any feedback.

**Comment by WanWizard** [comment]
Why did you use json, and not a serialized array? Mind if we use this as the basis for a core DB driver?

**Comment by iamacarpet** [comment]
JSON was used firstly because it was the class that seemed easiest to extend while I was learning how it worked and secondly it seemed a good idea for it to be easily humanly editable / readable incase we need to edit manually.

By all means, if you would like to use it please do. I'd be greatful if you could keep updates in this thread so we can update our implementation if you improve it.

**Comment by WanWizard** [comment]
Already created a driver. ;-)
