### ISSUE TITLE
default value in validated() in validation class dont work

### ISSUE THREAD

**Issue by patie** [fuel/core#154]
in validation class run() method is

```
$this->validated[$field->name] = $value;
```

so array is always exist

and now in validated() method is

```
return array_key_exists($field, $this->validated) ? $this->validated[$field] : $default;
```

result - $default never be used because key always exist. right ?
solution - I think it should be verified null value

**Comment by jschreuder** [comment]
Do you have any reason to believe this? The reason I ask is because you are completely wrong.

The whole thing is within a try-catch block and when a rule fails that assignment is never made.

**Comment by patie** [comment]
ok maybe im wrong but i dont know why default - dont work

**Comment by jschreuder** [comment]
Just tested it to be sure and works fine.

**Comment by patie** [comment]
testing too for some values it works and other dont.. I write more in a moment

**Comment by patie** [comment]
so.. when i use value="" in html its dont work must be nothing no value="" its null too but only as value not as type :/ 

must be === in      if ( $allow_partial && $value === null ) ?

**Comment by jschreuder** [comment]
Could you give a full code example of your validation code, I have no clue where to start looking based on this

**Comment by patie** [comment]
view
`
<input name="nazov_rewrite" value="<?php echo $validation->input('nazov_rewrite'); ?>" class="local"  />
`
controller
`
  $tovar = new Model_Tovar();
  $tovar->nazov = $validation->validated('nazov');
  $tovar->nazov_rewrite = $validation->validated('nazov_rewrite', \Inflector::friendly_title($validation->validated('nazov'), '-', true));
`

i set 
for "nazov" - blablabla
nothing for "nazov_rewrite" i leave it blank
submit form

```
echo $tovar->nazov; 

if ($tovar->nazov_rewrite==null)
{
echo 'nazov_rewrite is null';
}
```

OUTPUT:
blablabla
nazov_rewrite is null

**Comment by jschreuder** [comment]
First of all, with that code you're still not sure if it's null. It could just as well be zero, empty string, '0', false or empty array. (always use === is such a case)

Actually I think I know what the problem is, though I can't be sure as you included none of the validation code.

$validation->validated('nazov_rewrite') returns an empty string and that's probably valid. The second part is only used when the first value was never set, but an empty string is valid input unless you give it a rule named required.

What you want is this:

```
$tovar->nazov_rewrite = $validation->validated('nazov_rewrite') ?: \Inflector::friendly_title($validation->validated('nazov'), '-', true);
```

That means use the first part unless it's a false value (null, false, 0, '0', "", or array()) then it uses the second part (and if you're smart you also add trim to the rules to prevent just a space).

**Comment by patie** [comment]
ok you right, my bad.

thanks
