### ISSUE TITLE
Double urldecode issue in Input class on PUT, PATCH, & DELETE methods on form submissions

### ISSUE THREAD

**Issue by dustinbolton** [fuel/core#1557]
Under some circumstances the Input class will first run urldecode() on a variable and then follow it with parse_str().  Unfortunately this results in double decoding the data as the parse_str() has the undocumented 'feature' of running urldecode() on the parameters passed to it.  I discovered this when submitting a form via the PUT method and all my encodings of %2B were ending up as spaces.  They should end up as plus signs (+).  Logging the variables throughout this function shows that the urldecode() function runs which properly decodes %2B to + but then parse_str() runs and further decodes, resulting in plus signs (+) turning into spaces in my case.

In input.php's hydrate function(), the following code exists:

```
if (\Input::method() == 'PUT' or \Input::method() == 'PATCH' or\Input::method() == 'DELETE')
{
    static::$php_input === null and static::$php_input = file_get_contents('php://input');
    if (strpos(static::headers('Content-Type'), 'www-form-urlencoded') > 0)
    {
        static::$php_input = urldecode(static::$php_input);
    }
    parse_str(static::$php_input, static::$put_patch_delete);
    static::$input = array_merge(static::$input, static::$put_patch_delete);
}
```

As parse_str() handles decoding then I believe the following code may safely be removed to resolve this issue of inadvertently double-decoding so perhaps this is a simple fix:

```
if (strpos(static::headers('Content-Type'), 'www-form-urlencoded') > 0)
{
    static::$php_input = urldecode(static::$php_input);
}
```

**Comment by WanWizard** [comment]
It was added 5 months ago (https://github.com/fuel/core/commit/72e0661e74b409234e83a3fd3b750f6455733f53) based on a bug report that double decoding was needed.

Iirc, the issue was that if the header indicates the form data is www-form-encoded, it should be. Then on submission the entire data stream is urlencoded again. Which makes the form part of the payload effectively double encoded.

I've been through the IRC logs, but I can't find a discussion that triggered this commit.
