### ISSUE TITLE
Bug with crypt.php [Fuelphp 1.6]

### ISSUE THREAD

**Issue by Solovej** [fuel/core#1564]
Fuelphp 1.6

core\classes\crypt.php

line: 154

$mod4 = strlen($data) % 4;

If I will input array - php throws error because array is not allowed by strlen.

I will update this topic, because I have some other issues with array to "string".
Please do not close.

I think will be better if you will add to:  $mod4 = strlen($data) % 4
Something like that:
$foreach_data = '';
if(is_array($data)){
Log::warning('core\classes\crypt.php -> safe_b64decode received array, but should be string!');
foreach($data as $key => $value){
$foreach_data .= $key.$value;
}
}

$data = $foreach_data;

**Comment by WanWizard** [comment]
That is an internal class method that base64 encodes a string.

As far as I can see you only get there when you try to decode() an array instead of a string. Since the result of an encode() is ALWAYS a string, you have a validation issue in your code. Both encode() and decode() only accept string values, see the documentation. 

This is not a framework issue, and it is not the task of the framework to protect you from coding errors (the framework would become dead slow if we would do that).
