### ISSUE TITLE
Closure as an argument in Fieldset_Field add_rule doesnt thrown Validation_Error 

### ISSUE THREAD

**Issue by hugomrdias** [fuel/core#157]
Example code:

``` php
$val->add('password', 'Password')
     ->add_rule('required')
     ->add_rule('min_length', 3)
    ->add_rule('max_length', 20)
    ->add_rule(function($val){
        return $val == 'test'? true:false;
    }
);
```

Error : 
ErrorException [ Error ]: Cannot use object of type Closure as array

COREPATH/classes/validation/error.php @ line 75

**Comment by jschreuder** [comment]
I'll add support for this in 2 ways:
- closure will get a generic "closure" function name for error messages
- it will be possible to pass closures as something like `array('closure_name' => function($val) {/*etc*/})` to give it a specific name - gotta think about the exact way to do this so I'm open to suggestions

**Comment by dhrrgn** [comment]
Make the name of the rule first, then make the closure the argument:

``` php
$foo->add_rule('my_test', function($val) {
    return $val == 'test' ? true : false;
});
```

Simplez.

**Comment by jschreuder** [comment]
@dhorrigan currently the add_rule() method takes a callback in the first arg and arguements for the callback as 2nd, 3rd, etc. The way you propose would make the whole thing ambiguous because it would need to test the 2nd arguement before figuring out if the first arg is a valid callback, and you couldn't pass a closure to the callback as the first arg anymore. (actually 2nd as the first arguement will always be the value to validate)

[edit] To clarify further:

``` php
<?php
$foo->add_rule($arg1, $arg2, $arg3, $arg4);

// will be called like this:
call_user_func_array($arg1, array($value, $arg2, $arg3, $arg4));
// or when the first arg is called on a validation 'callable'
call_user_func_array(array($callable, '_validation_'.$arg1), array($value, $arg2, $arg3, $arg4));
```
