### ISSUE TITLE
Validation rule 'required' returning a false positive. 

### ISSUE THREAD

**Issue by bradhanebury** [fuel/core#1668]
In the docs, it says that the required validation rule means the field being tested is set and that it has been given a value other than null, false, or an empty string. However, in the core/classes/validation.php file starting at line 469 in the _run_rule method

```
protected function _run_rule($rule, &$value, $params, $field)
{
    if (($rule = $this->_find_rule($rule)) === false)
    {
        return;
    }

    $output = call_user_func_array(reset($rule), array_merge(array($value), $params));

    if ($output === false && $value !== false)
    {
        throw new \Validation_Error($field, $value, $rule, $params);
    }
    elseif ($output !== true)
    {
        $value = $output;
    }
}
```

Specifically, line 478 that checks the output to see if it is false or if the value is NOT equal to false. If the $rule param is 'required' and the value is false, then line 478 will not throw a validation error, which I feel it should. 

For example, if I do the following:

$val = Validation::forge();
$val->add('first_name')->add_rule('required');
$params = array('first_name' => false); 
$val->run($params); 

The above required rule will return passed, even though the first_name field is not something other than null, false, or an empty string as stated in the docs.

**Comment by it-can** [comment]
If this is indeed an error, it should be tested for in phpunit...

**Comment by WanWizard** [comment]
Well, that is open for debate.

You could argue that 'required' means 'present', in other words the result of a `array_key_exists`. It could have a `""`, `false` or `null` value, but still, that is a value. 

For custom input of validation, I would prefer it this way. If you would like a non-empty string, you should validate it's contents, not simply check if it's there.

For validation of POSTed input, everything is a string, and you could debate that required means a non-empty string, because from an HTML form point of view, that is what 'required' means.

That however makes the behavior different depending on whether or not you pass an array to validate. And what if you pass `\Input::post()` ?

**Comment by mikepmtl** [comment]
IMHO false is a value and should pass.  
Null should not pass.
