### ISSUE TITLE
Database method list_tables() is not supported by PDO driver

### ISSUE THREAD

**Issue by Art4** [fuel/core#1704]
Using DB::list_tables() with PDO driver fails with an Exception:

`Fuel\Core\FuelException [ Error ]: Database method Fuel\Core\Database_PDO_Connection::list_tables is not supported by Fuel\Core\Database_PDO_Connection`

After a code sight it seems to me [it was never implemented](https://github.com/fuel/core/blob/73d4a0fe64bdaf58d1b92040da99abe846a796dc/classes/database/pdo/connection.php#L311).

**Comment by WanWizard** [comment]
Correct. Which is why it throws an exception. 

And the reason is very simple: the DB actions to perform to list all tables are highly dependent on the RDBMS platform in use. And since the PDO driver is a generic driver, you can not make assumptions about the underlying RDBMS.

If you have a specific target platform in mind you want to access through PDO, extend the PDO driver, and overload the list_tables() method with SQL for that specific platform.
