### ISSUE TITLE
Sessions should use locking.

### ISSUE THREAD

**Issue by rickmacgillis** [fuel/core#1809]
The lack of locking capabilities in sessions make it impossible to use them as a storage method for Ajax requests and the like. Concurrent requests will sequentially overwrite each other. Locking is a perfect way to bypass this update conflict issue if you can figure out a way to handle this.

I just spent the whole day troubleshooting a script that wasn't even broken. The infrastructure was. Please fix this issue so Ajax requests are able to store this data. I hope this saves someone else some time.

**Comment by WanWizard** [comment]
On the contrary, if you implement locking, all your requests are processed sequentially, and if your application is heavy on ajax, it grinds to a halt. The lack of locking, and the main reason not to implement PHP native sessions (which implicitly lock), is exactly because of that. Also, most of the session backends we have drivers for don't even support locking, or have locking with huge side-effects.

The downsite of this is that you have to take it into account when writing your application, since as you have noticed concurrent updates might conflict.

So the infrastructure isn't broken, it's by design. And it will not be changed.
