### ISSUE TITLE
Logging bug?

### ISSUE THREAD

**Issue by chriskoo** [fuel/core#1845]
Hello, I've create a fuel task for continue working.

The task is start on 5/27/2015 , each logging is append the fuel/app/logs/2015/05/27.php.
As  the time elapse, the date is change to 5/28/2015, I mention the logging is still append to the fuel/app/logs/2015/05/27.php.

Is there a bug ? And is there any way to solution the problem while logging with long time task ?

**Comment by WanWizard** [comment]
Not a bug, you bump into it because it's not made for long term of daemonized tasks. The name of the logfile is determined in the constructor of the log class, so that happens only once per class load.

In general, you create a task to perform a single ... eh ... task, and you use an external scheduler to loop or restart, or some sort of task queue mechanism that fires the individiual tasks.

Long running tasks have another side effects, PHP caches a lot, so things might go horribly wrong if you update the framework or your app while the task is running. You have similar issues if you need to run migrations, so your code is updated but your db schema isn't yet.

**Comment by WanWizard** [comment]
p.s. the constructor of Log is static, so you could rotate the log manually from within your task using `\Log::_init();`
