### ISSUE TITLE
Db::query result doesnt map to proper variable type

### ISSUE THREAD

**Issue by badoet** [fuel/core#1864]
since upgrading to 1.7.2, the DB::query convert int value in the db into string.
causing lots of breaking and errors everywhere
and its not consistent.
most of it affect TINYINT and BIGINT Unsigned
INT type seems fine.
but the BIGINT is intermitten. it is converted as int and string
i have 2 separate call with different join condition resulting in int for one and string for the other.
help?

**Comment by WanWizard** [comment]
I think you are wrong, Fuel doesn't do anything. 

PHP's database drivers (especially MySQL) have always returned **ALL** data as string, and DB doesn't do any type checking or conversion. The ORM does if you use the observer_typing.

The DB layer in Fuel hasn't changed much since it was introduced, now over 4 years ago.

**Comment by huglester** [comment]
Maybe you used to use php5-mysqlnd over php5-mysql?

Because if I am correct php5-mysqlnd extension supports integers

**Comment by WanWizard** [comment]
I'm using PDO here, PHP v5.6.7, and there is it still the case.

But the message is: Fuel passes whatever it gets passed by the drivers. If the values is string, a string is  passed on, if the value is an integer, an integer is passed on. No processing happens in the DB layer.

```
      protected '_data' => 
        array (size=7)
          'id' => string '1' (length=1)
          ....
```

**Comment by WanWizard** [comment]
@badoet do you have example code?

**Comment by WanWizard** [comment]
Closed due to no response.
