### ISSUE TITLE
updating composer.phar using compressed zip file

### ISSUE THREAD

**Issue by nasserman** [fuel/core#1876]
I download fuelphp.1.7.3 from main site, then extracted it as mentioned in docs//installation/instructions.html.

then : php composer.phar seflf-update
also i changed composer.json to this
....
    "require": {
        "php": ">=5.3.3",
        "composer/installers": "~1.0",
        "fuel/core": "dev-1.7/master",
        "fuel/auth": "dev-1.7/master",
        "fuel/email": "dev-1.7/master",
        "fuel/oil": "dev-1.7/master",
        "fuel/orm": "dev-1.7/master",
        "fuel/parser": "dev-1.7/master",
        "fuelphp/upload": "2.0.2",
        "monolog/monolog": "1.5.*",
        "mustache/mustache": "~2.5",
        "michelf/php-markdown": "1.4.0"
    },
....
then run : php composer.phar update
updating terminated with this result : 

Loading composer repositories with package information
Updating dependencies (including require-dev)  
Deleting docs - deleted
- Installing mustache/mustache (v2.8.0)
  Loading from cache
- Updating fuel/core dev-1.7/master (e8c221a => f614b30)
  
  [RuntimeException]  
  The .git directory is missing from fuel/core, see https://getcomposer.org/commit-deps for more information  

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]

i think some thing is wrong with downloaded zip file,

so i renamed core folder to core2 and packages/orm to packages/orm2, and run "composer.phar update" again, it works well,

i think it is not a bug or issue in fuelphp, just an issue in packing fuelphp.zip,

**Comment by WanWizard** [comment]
The zip file you download does not contain any repositories, so you're not supposed to have composer update the fuel files.  It is meant to run Fuel without any additional dependencies. So the composer.json that is included is not correct.

**Comment by nasserman** [comment]
so... if any one downloads zip file, he could not use composer? or what is his next step to add packages like mustache?

**Comment by kenjis** [comment]
@WanWizard Did you removed `.git` folder before creating Zip file?

I recommend to create Zip file like this:

```
$ composer create-project fuel/fuel:dev-1.7/master fuelphp-1.7.x --prefer-dist
```

**Comment by nasserman** [comment]
@kenjis i used your command for creating a folder contains fuelphp and without any problem run self-update & update command for installing new package (mustache), thank you very much,

just for testing i extracted downloaded zip file (from main site) and after self-update, add my package name to composer.json and just update that package (composer.phar update mustache), 

why main site's zip file did not created this way (using --prefer-dist)? is it necessary to edit zip file or add some help to documentation?

**Comment by kenjis** [comment]
@nasserman The official Zip file seems to be broken. I reproduced your error.

I think it would be better to fix the Zip file.
If we install via Zip, we can't use Composer. That is non sense.

**Comment by WanWizard** [comment]
No, if you install the zip, all Fuel files are static. You should be able to use composer, but not to do something with Fuel. After all, you have installed 1.7.3., and that will remain that version forever. It has always been like this.

So the problem is that the composer.json file in the zip contains references to Fuel repo's (and others included in the zip), and those have to go.

If you want a complete installation managed by composer, you don't install the zip. You clone the fuel repo and let composer do the rest.

**Comment by nasserman** [comment]
@WanWizard i agree, that version 1.7.3 must be static, but 2 question, what if any one wants to upgrade fuelphp installation to newer version? so, composer.json must change so it be possible to add other packages by composer.
but what is wrong aboute --prefer-dist ?

**Comment by kenjis** [comment]
I've created fixed Zip file: http://fuelphp1st.com/downloads/fuelphp-1.7.3-fixed.zip

```
$ composer create-project fuel/fuel:dev-1.7/master fuelphp-1.7.3 --prefer-dist
$ zip -r fuelphp-1.7.3-fixed.zip fuelphp-1.7.3 
```

If you use the official Zip:

```
$ unzip fuelphp-1.7.3.zip
$ cd fuelphp-1.7.3
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                          
  - Updating fuel/core dev-1.7/master (e8c221a => f614b30)

  [RuntimeException]                                                                                  
  The .git directory is missing from fuel/core, see https://getcomposer.org/commit-deps for more inf  
  ormation                                                                                            

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]
```

If you use the fixed Zip:

```
$ unzip fuelphp-1.7.3-fix.zip
$ cd fuelphp-1.7.3
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                          
Nothing to install or update
Generating autoload files
```

**Comment by kenjis** [comment]
@WanWizard `fuelphp-1.7.3-fix.zip` has no git repositories.

The current official Zip file prevents users from using Composer. And it has no merit.

**Comment by nasserman** [comment]
@kenjis thank you kenjis , you helped me,
@WanWizard 3 ways for installing fuelphp must have same results, it is not good.

**Comment by WanWizard** [comment]
The zip file was and is created for people that don't know what git is, that do only something locally, and possibly ftp everything to a 1-bit hoster. People that don't know what composer is, or have no commandline access and can not run composer.

It has never contained any .git directories, and it never will. If only because you will include 5 year of development history that will explode the size zip file. And since people should be able to use it without  composer, you also need to include all other external components, making it even worse.

The docs are very clean at this point: there are 4 different ways of installing Fuel documented, and using the zip file is the last of those 4.

So every reference to both fuel components and external components that are required have to be removed from the composer.json in the zip. It will still allow you to run composer for additional components, and will not give an error.

If you want to use composer, if you want to use git, do not use the zip. It's as simple as that.

**Comment by kenjis** [comment]
@WanWizard 

> It has never contained any .git directories, and it never will. 

The Zip I created has no .git directories.

> And since people should be able to use it without composer

People can use it without composer.

> So every reference to both fuel components and external components that are required have to be removed from the composer.json in the zip. It will still allow you to run composer for additional components, and will not give an error.

Why you have to remove?

**Comment by kenjis** [comment]
To use or not to use Composer is user's choice. It is okay.

But you say people who installed via Zip should not update Fuel via Composer.
For what?

**Comment by WanWizard** [comment]
I was not responding to you, we say the same thing. I was responding to @nasserman and explaining why the zip has no git directory.

**Comment by kenjis** [comment]
I am just asking because I don't get what you think. And if you don't respond, I don't get it.

What's wrong if people who installed via Zip could update via Composer?
Of course you have the right of silence. No problem :-)

> So every reference to both fuel components and external components that are required have to be removed from the composer.json in the zip. It will still allow you to run composer for additional components, and will not give an error.

After all, we have to say the official Zip file is now broken.

**Comment by nasserman** [comment]
I am not a professional programmer (and i am not very newbie), i did  not used composer before but used git for my little apps, i installed fuelphp without any problem using zip file but i spent 2-3 hours for installing mustache (installing it using composer in zip installation), i am saying that a new user that want to learn or use fuelphp (every professional was beginner at start) must has a clear way,
if you think zip file must be solid or must be update-able  or any other, you know how it can be implemented and how it is better, but make it (installing, using, extending, adding packages, ... ) simple and easy as possible.
@WanWizard still i don't know why kenjis's way to create zip file is not good?
composer create-project fuel/fuel:dev-1.7/master fuelphp-1.7.3 --prefer-dist

**Comment by nasserman** [comment]
I am not a professional programmer (and i am not very newbie), i did  not used composer before but used git for my little apps, i installed fuelphp without any problem using zip file but i spent 2-3 hours for installing mustache (installing it using composer in zip installation), i am saying that a new user that want to learn or use fuelphp (every professional was beginner at start) must has a clear way,
if you think zip file must be solid or must be update-able  or any other, you know how it can be implemented and how it is better, but make it (installing, using, extending, adding packages, ... ) simple and easy as possible.
@WanWizard still i don't know why kenjis's way to create zip file is not good?
composer create-project fuel/fuel:dev-1.7/master fuelphp-1.7.3 --prefer-dist

**Comment by WanWizard** [comment]
@kenjis if I don't respond, there might be other things at play. I might simply be sleeping, I've been very ill for the last year, and don't have the energy anymore to work around the clock like I used to.

Who am I to dicate what other people should do? All I am saying that this is the reason we created the zipfile, and we expect people that want to use composer to know what git is, and use one of the installation methods that result in a local git clone.

@nasserman the scripting to create the zip was make before there was composer, and it was never adapted. And because of the aforementioned issues, I never have.

There is nothing wrong with the created zip, and I'll will update it when I have an opportunity.

**Comment by WanWizard** [comment]
New zip is online.

**Comment by kenjis** [comment]
Thank you for your quick Zip update. I've confirmed `composer update` gives no error.

I don't expect quick response. Sleeping is very important to human beings.

**Comment by nasserman** [comment]
thank you
