### ISSUE TITLE
Problem with using phpseclib from composer

### ISSUE THREAD

**Issue by craftpip** [fuel/core#1951]
Hello,
I installed flysystem, that uses phpseclib for its sftp functionalities,
So i have noticed composer installed phpseclib as its dependencies. 

When i try to use the flysystem library i get the error:

```
COREPATH/vendor/phpseclib/Net/SSH2.php" does not contain class "phpseclib\Net\SSH2"
```

Apparently there are two copies of phpseclib in Fuel now, and Flysystem is using the one in the Fuel's Core directory.

How do i overcome this? Thank you.

**Comment by kenjis** [comment]
`COREPATH/vendor/phpseclib` was removed yesterday. Try the latest `1.8/develop` branch.

**Comment by craftpip** [comment]
Do i need to update the other components like Auth, Email, Oil also to `1.8/develop` ?
My current version is `1.7/master`

**Comment by WanWizard** [comment]
The problem here is that the included version of PHPSecLib is from before the composer package. At that time it was not namespaced, and we decided to move it to the "phpseclib" namespace.

The composer package uses the same namespace, violating the general rule that you use "vendorname\packagename" for your composer namespace.

If you upgrade your core to 1.8/develop, I suggest you upgrade the other packages too, for consistency. Only the Auth package has a phpseclib dependency, so that one MUST be upgraded.

If you do so you  also get PHP7 compatibility.

**Comment by craftpip** [comment]
Alright, so now i understood the problem, it was helpful.
Thanks for the support :)

**Comment by craftpip** [comment]
Hello, 
After upgrading to `1.8/develop` i get the following error 

```
Mustache_Exception_RuntimeException [ Error ]: FilesystemLoader baseDir must be a directory: UTF-8
```

```
DOCROOT/fuel/vendor/mustache/mustache/src/Mustache/Loader/FilesystemLoader.php @ line 57
```

**Comment by WanWizard** [comment]
That suggests a Mustache error, not a FuelPHP error?

**Comment by WanWizard** [comment]
Your basedir isn't set correctly. 

See https://github.com/bobthecow/mustache.php/blob/master/src/Mustache/Loader/FilesystemLoader.php#L48

**Comment by craftpip** [comment]
I got it, Thanks for the great support, love fuel. :+1:
