### ISSUE TITLE
bug with russian symbols in Inflector::friendly_title

### ISSUE THREAD

**Issue by almor** [fuel/core#1980]
`Inflector::friendly_title('русский язык', '-', true);`
result: 'usskij-jazyk' it`s wrong, must be '**r**usskij-jazyk'

My solution:
call        

```
// Replace apostrophes.
        $str = preg_replace("#[\’]#", '-', $str);
```

after

```
        // Only allow 7bit characters
        $str = static::ascii($str, $allow_non_ascii);
```

**Comment by WanWizard** [comment]
Not even sure why those apostrophes are stripped there, since they are non-ascii, so they are replaced by the separator later on.

Assuming your string is `this ’is’ a test`, the result will be `this-is-a-test`, with or without apostrophes removed, so ihmo this is rather pointless.

The only slight difference is in a string like `ab’cd`. With  apostrophe removal, this becomes `abcd`, without, this becomes `ab-cd`. So not sure the first one is better...

**Comment by WanWizard** [comment]
@stevewest you have any opinion on this?

**Comment by WanWizard** [comment]
Forget it, the apostrophe isn't stripped, it's replaced by the separator, so it doesn't matter, result will be the same.
