### ISSUE TITLE
Request method DELETE throws error

### ISSUE THREAD

**Issue by nakedgen** [fuel/core#2022]
after last update in Core\Classes\Input\instance.php in last condition at the end of file added **strtolower**

`
if ($this->method() == 'PUT' or $this->method() == 'PATCH' or $this->method() == 'DELETE')
        {

$this->{'input_'.strtolower($this->method())} = $php_input; // throws error in all() method
            $this->{'input_'.($this->method())} = $php_input; // working correctly
        }
`

**Comment by WanWizard** [comment]
What exactly is the error?

**Comment by WanWizard** [comment]
Is this better?

```
        $method = strtolower($this->method());
        if ($method == 'put' or $method == 'patch' or $method == 'delete')
        {
            $this->{'input_'.$method} = $php_input;
        }
```

**Comment by WanWizard** [comment]
To be complete, the reason why the old code, and your suggestion, doesn't throw an error, is because it creates `$this->input_DELETE`. And since class properties are case sensitive, the input is effectively discarded because the rest of the class uses `$this->input_delete`.

So if the fixed code throws an error, I'm interested in the error, and the contents of $php_input, because chances are it doesn't contain an array, and we need to find out why.

**Comment by WanWizard** [comment]
This issue has been addressed over the weekend.
