### ISSUE TITLE
csrf_expiration sometimes causes mismatch when set to zero

### ISSUE THREAD

**Issue by forestlovewood** [fuel/core#2042]
I spent about two hours today trying to figure out why I was getting a csrf token mismatch on every form on a web application. After a lot of debugging and pulling my hair out, I discovered that having csrf_expiration set to zero, which seems to be recommended in the docs, can cause random and serious issues, which were only resolved by setting a positive integer as the expiration time.

I ended up using 7200, since Laravel uses it with no problems, and sure enough the application works fine. Either the default needs to be a non-zero integer, or there needs to be clearer instructions in the documentation that it needs to be manually set.

**Comment by WanWizard** [comment]
Just randomly checked about 5 of our applications, and all use the default of 0. And not a single complaint, so I am very interested in your "random and serious" issues. It sounds a bit like you open multiple forms, and have forgotten to add the token update code to your forms.

Setting the expiration to 7200 basically disables token rotation, which is a potential security risk, the main reason why Fuel by default rotates to token on every use. You might want to look at http://fuelphp.com/docs/classes/security.html#/method_js_set_token

**Comment by forestlovewood** [comment]
Okay, that makes sense. I was under the impression that the security worked on a per-form basis as opposed to an application-wide basis. I believe I did have multiple windows open, so that will have been rotating the token. By random and serious issues, I was referring to the csrf token mismatch error, which would occur randomly and then persist until the browser was restarted, regardless of clearing cookies or deleting server based sessions.

I will need to double check, but it's much more likely, as you say, that it was my own mistake. Thank you for your response.

**Comment by WanWizard** [comment]
For more info on how it works, see https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#CSRF_Specific_Defense

We have implemented "Synchronizer (CSRF) Tokens", which by default are expired when used instead of per user-session. This is more strict than OWASP suggests, but we want the default to be as secure as possible. 

The default setting does mean that the token will expire as soon as it is used (i.e. a protected form is submitted). It has the downside that when you have multiple forms open at the same time, you have to make sure the token in the form is up to date (by using that snippit of javascript) before it is submitted. 

You can switch to the OWASP per-user-session token by setting "csrf_expiration" to 0. Setting it to another value does lengthen the validity period of a generated token, but it will still expire it as soon as it is used (which is why it didn't fix your problem).
