### ISSUE TITLE
ErrorHandler does not pass exception as context to Monolog

### ISSUE THREAD

**Issue by Josh-G** [fuel/core#2044]
Hi,
We are running a production system across a few machines and are using Sentry for centralised logging. However, when an error is handled, the exception is not passed to Monolog and on to Sentry so we are unable to see stack traces. 

It's possible to work around this by using the Raven errorhandler however it causes duplicate errors in sentry, some with stacktraces and some without. Please could you advise how we could work around this?

Thanks.

**Comment by WanWizard** [comment]
Are you referring to something like this? http://stackoverflow.com/questions/20657309/logging-full-stack-trace-with-monolog

**Comment by Josh-G** [comment]
Hi WanWizard, thanks and apologies for delay in response. I've provided a simple version of adding the handler to the monolog instance below, which isn't working for us currently.

log.php
http://pastebin.com/pMeurkmt

bootstrap.php
http://pastebin.com/jjd6wP6r

Then a controller throws an unhandled exception and the exception appears in sentry but without a stacktrace:
https://sentry.io/share/issue/3133333032352e323039363432333535/

**Comment by WanWizard** [comment]
Ok.

Looking at the Monolog code in detail, it seems that it expects the entire exception object to be passed. Fuel's log class however is completely written for string messages, so rewriting this may involve quite a bit of work.

**Comment by WanWizard** [comment]
Can you verify this solves your problem?

**Comment by Josh-G** [comment]
Thanks for the quick turnaround on this, it's awesome! I'll be able to check this commit shortly but looks like it'll do what we're expecting.

**Comment by WanWizard** [comment]
Cool, let me know so I can update the docs with this new feature.

**Comment by Josh-G** [comment]
Thanks, almost there. So this gives us the stacktrace now in in Sentry, as Monolog will cast the exception to a string, however Monolog has the concept of a context for each logging message, and by adding the exception to the context, Monolog handlers can perform additional processing based on the records in the context array.

For example, the RavenHandler can provide source code snippets around lines from the stacktrace, some argument information etc. There's quite a few things that monolog will recognise as context for a record.

I have a patch where I've got the intended behaviour, however I have modified logger() in order to achieve this, by adding a fourth parameter; 
`logger($level, $msg, $method = null, $context = []) `
If this is an acceptable change I will create a pull request.

**Comment by Josh-G** [comment]
Additionally, a simpler fix would be to change https://github.com/fuel/core/blob/1.9/develop/classes/log.php#L282
to:
`static::instance()->log($level, $msg, array('exception' => $msg));`

**Comment by WanWizard** [comment]
That doesn't work, that would make every log entry an exception.

Altough now that we're using Monolog it sounds a bit weird, but `$method` is supposed to be the context you refer too. So that has to  be passed to the log handler correctly, by both the Error handler and the Exception handler.

**Comment by WanWizard** [comment]
Pushed another update. Perhaps not as generic as you hoped for, but I need to keep an eye on the output of other logs handlers as well, and of the profiler to which the log entries are written too.

**Comment by Josh-G** [comment]
Sorry to be a pain, but the latest commit didn't resolve the issue. I have provided a pull request in #2046 which allows additional contexts to be passed to monolog via Log::write and it adds the exception under the 'exception' key of the context array, which enables Raven to do the exception parsing.

> Perhaps not as generic as you hoped for, but I need to keep an eye on the output of other logs handlers as well, and of the profiler to which the log entries are written too.

Absolutely, I'm hoping to to get this merged with the least impact as possible :)

Please let me know if you'd like me to adjust the pull request or if it's no good. Thanks.

**Comment by WanWizard** [comment]
How does that solve PR your problem? Errors and Exceptions are generated, and logged, by our ErrorHandler. You may want to add an additional argument to the `write()` method, but since no single line of code in Fuel will pass that argument, it's pretty pointless, it will always be an empty array(). My latest commit will call `Log()` with an array (throwablename => throwable object), so why doesn't that work?

It is beginning to sound more and more like a specific requirement of your app / your environment, which you can solve by overloading the Log class, and overload the `write()` method to check if the `$msg` passed is a throwable object, and if so, create your context array and log it. I don't really see the point of making this specific hardcoded change, just to accomodate your specific use case.

Something simple like this would do if you want a more general context:
````php
public static function write($level, $msg, $method = 'INFO')
{
    if ($msg instanceOf \Exception)
    {
        $method = 'exception';
    }
    elsif ($msg instanceOf \Error)
    {
        $method = 'error';
    }

   return parent::write($level, $msg, $method);
}
````

The only thing that might be debatable, is if the current third argument, which is meant to pass context, should also be allowed to be passed an array in case you want to pass more than one context. But no normal log mechanism would be able to deal with that, since they have string output (log files, syslog, sms, etc). So if array's are acceptable, you have just reversed the problem.

**Comment by Josh-G** [comment]
Sorry, I think I've confused things a little. The way I understand it at the moment, I think there's two related issues here, I believe it is difficult to access the ability to provide context to log records, as it requires extending the core class as you've discussed above. It's a nice feature of monolog and I think it should be as accessible as possible, and I would personally be in favour of extending the third parameter of write to accept an array which is passed as the context, as it is unclear to me what the purpose of the method argument is at the moment. This will allow developers to provide additional context to monolog handlers. The monolog handlers will be the classes that decide what happens with the context array, for example the LineFormatter will only print the context items when context is set in the format;
https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/LineFormatter.php#L80

Secondly, setting the context as the current master commit is doing is great, but no monolog handler will handle a context item name after the throwable. There are certain values that monolog handlers will process to provide the additional information (for example the stacktrace parsing available in sentry). I've listed a couple of examples below that take 'exception' as a standard context item for an exception.

- This is the handler I'm using: https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/RavenHandler.php#L183
- https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/RollbarHandler.php#L99
- A test case in monolog using context: https://github.com/Seldaek/monolog/blob/7ce63f964426a57b6a1c213d45e05eef1f013c54/tests/Monolog/Formatter/LineFormatterTest.php#L129

Other handlers have other context values they use, but they are definitely more specific and would absolutely be provided by developers rather than the framework, but I definitely think there is a case for providing the standard exception context as it will allow Fuel to work out of the box with Sentry/Rollbar/Airbrake servers etc without having to extend core framework classes.

I disagree that it's specific to our environment/app as passing context in this fashion is fairly typical:
https://github.com/php-fig/log/blob/master/Psr/Log/LoggerInterface.php#L122

and the use of the 'exception' context exists in the native monolog handlers and frameworks integrating with Monolog exists at least in Symfony:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php#L110

I see it more as closer integration to Monolog and the various services it supports natively :)  Apologies again, hope I'm making sense.

**Comment by WanWizard** [comment]
Quite possible, it happens to me quite frequently that I totally miss the point in discussions... ;-)

A bit of history: before we switched to Monolog in Fuel v1.5, the Log class only did file logging (the current default behaviour). Littered in the code, you find lines like:
````php
logger(\Fuel::L_INFO, 'Called', __METHOD__);
````
which creates log entries like
````
INFO - YYYY-MM-DD HH:MM:SS --> \Fuel\Core\SomeClass::SomeMethod - Called
````
So this is where the variable name `$method` came from. It is basically used as a sort of context, but as only class/method names were passed, the author of the original `Log` class picked this parameter name.

Now, if `write()` is modified and `$method` is changed to `$context`, which sounds logical, it should accept both strings (which is what Fuel internally sends) and array's (which you want to use if you want to log in your app). So far, that is not much of a problem, `write()` could convert the string to some sort of default context, and the default LineFormatter config could be changed to print that context. So far, so good.

Now, to the challenging part: Throwables.

These are logged from Fuel's `ErrorHandler` class. It is not a problem to have the error handler log `['error' => $object]`, and the exception handler  `['exception' => $object]`, but what happens when this gets to the `LineFormatter`? 

As you mentioned, if you have a context array, you need to specify the contexts used in the log string so they won't be skipped, but now we have 3 possible contexts, but only one log line? The test you linked to doesn't use any log string formatting at all, and still the exception is logged. So I'm a bit confused about this, I have to play with it a bit to see if I can come up with something usable, and most important, doesn't break backward compatibility.

**Comment by Josh-G** [comment]
Ah, I understand now :) If the method was to become a value in the context array, it would definitely break backwards log behaviour. Currently, the default lineformatter in log.php will not include context, however if context was to be added and method was added to context, the format of log lines would change.

I've had a quick look at how the format would change for existing log entries and provided a paste of how it currently looks how it could potentially end up looking. I've provided a call to both logger() and thrown an exception to see the difference between the two, added the exception to the context and then added some junk to the context as an example of some other potential context keys that developers may opt to provide for other handlers:
without context: http://pastebin.com/s2t1XvaP
with context: http://pastebin.com/0knTGkqT

> It is not a problem to have the error handler log ['error' => $object], and the exception handler ['exception' => $object], but what happens when this gets to the LineFormatter?

The handlers will expect the exception to always be in 'exception' and will ignore a 'error' key. A lineformatter with context specified in the format string will cast the context array to a string, including the exception within the string _as far as I'm aware_.

Adding the throwables to the context array would change backwards behaviour if devs have overridden the log class and added a formatter containing %context%, however they will _likely_ be expecting to handle context values if they have done this, however this shouldn't affect the current default log.php lineformatter. I think that the default lineformatter should not print the context array as I believe this is more useful for passing values to handlers than to be printing with the formatters, and is quite ugly for printing.

I think that the best way to go would be a breaking change (2.0?) to implement monolog context and have $method become an array context, but in the meantime, I think a non-BC change could be made to provide access to the context. 

I'm not sure if this helps at all?

**Comment by WanWizard** [comment]
I think I can live with the format of the log line itself, it's only text, if someone is parsing that, they're using the wrong Monolog handler. ;)

The biggest issue is indeed people that have overloaded the `write()` method. I'll have to give this a proper think tomorrow, and test some scenario's. Thanks for the input sofar.

**Comment by Josh-G** [comment]
Thanks WanWizard, I'm glad I could provide some input, I'm interested in knowing what comes of it! :)

**Comment by WanWizard** [comment]
Pushed a new solution.

It will call monolog with a context array on error's and exceptions, and with a string for backward compatibility. It also introduces `\Log::log()` which allows your code to log with context directly.

Let me know what you think.

**Comment by Josh-G** [comment]
> It also introduces \Log::log() which allows your code to log with context directly.

This is perfect :) Developers can now use all kinds of contexts in monolog handlers, from notification sounds in pushover to attachments in Slack.

> It will call monolog with a context array on error's and exceptions

Only thing to note here is that currently the errorhandler is setting $context['error'] for errors and $context['exception'] for exceptions, but the monolog handlers only look for $context['exception'], where they check for both Exception or Throwable (in 7), so you get this for exceptions:
![Exception](http://imgur.com/HHXEzpK.png)
and this for errors currently:
![Error as error](http://imgur.com/5B2ykZW.png)
If it's sent through as an 'exception' then it will have the same stacktrace parsing:
![Error as exception](http://imgur.com/pTFd3Fs.png)
We can just overload log write and re-write errors to exceptions in the context array, but I don't think it makes sense to keep the two different keys as the error one is not used by any handlers. My explanation is probably crap so here's the source code I mean;
https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/RavenHandler.php#L183 (same for rollbar, browserconsole etc)

Otherwise this is perfect, thanks for your work on this :)

**Comment by WanWizard** [comment]
Ok, thanks for the feedback, I'll adjust accordingly.
