### ISSUE TITLE
Two github organizations fuel and fuelphp

### ISSUE THREAD

**Issue by craftpip** [fuel/core#2058]
I noticed that there are two organizations made for fuel
https://github.com/fuel and
https://github.com/fuelphp

fuel seems to be the current one on which v1.x is being developed, 
and fuelphp is where v2 is being developed ?

Thanks

**Comment by Art4** [comment]
This is correct.

**Comment by WanWizard** [comment]
Yup. Because the repo structure for v2 is completely different, we decided to create a different organisation for it. 

This is temporary, as soon as v2 is released and v1 is declared end of life, the repo's will probably be moved, the PHP organisation doesn't like the accronym to be used in products...
