### ISSUE TITLE
problem when convert time(%H:%M:%S) to other timezone with Date class

### ISSUE THREAD

**Issue by huuphuc2401** [fuel/core#2084]
I'm using Centos 7, php 5.4.16
I got problem when convert time to other timezone with Date class
```php
// in config.php: 'default_timezone'   => 'Asia/Tokyo' //UTC+09:00
$time = Date::create_from_string('10:00:00', '%H:%M:%S');

// Asia/Singapore UTC+08:00
echo $time->set_timezone('Asia/Singapore')->format('%H:%M:%S'); //display 07:55:25 (Expected 09:00:00)

// Asia/Seoul UTC+09:00
echo $time->set_timezone('Asia/Seoul')->format('%H:%M:%S'); //display 09:30:00 (Expected 10:00:00)

// Asia/Ho_Chi_Minh UTC+07:00
echo $time->set_timezone('Asia/Ho_Chi_Minh')->format('%H:%M:%S'); //display 08:06:40 (Expected 08:00:00)
```

**Comment by WanWizard** [comment]
This seems to be related to the the fact that because of the fact you don't pass a date, only a time, the date of "01-01-1900" is used. 

If you then move backwards in time by applying a timezone, you get to a date before the unix epoch (in this case "sunday 31 dec 1899 10:00:00 AMT", which causes weird things to happen.

**Comment by huuphuc2401** [comment]
@WanWizard thanks for your explanation
