### ISSUE TITLE
What is the Future of the FuelPHP framework?

### ISSUE THREAD

**Issue by rotexdegba** [fuel/core#2117]
Hi there,

Not sure if this inquiry belongs here, but I am posting it here for now.

I have an application that was developed using FuelPHP 1.7 and recently upgraded to FuelPHP 1.8.1. The application is currently in maintenance mode (bug fixes and some few new features being implemented once in like every 6 months).

I have personally moved on to SlimPHP 3 and other [PSR-7](https://www.php-fig.org/psr/psr-7/) compliant packages for my new projects (I actually developed my own MVC framework based on SlimPHP 3 https://github.com/rotexsoft/slim3-skeleton-mvc-app).

I am just wondering if there are any plans for a FuelPHP 2.0 framework and if so, will it be PSR-7 based?

Thanks for the anticipated feedback!

**Comment by JefferyHus** [comment]
I believe if all Fuel fans start contributing we may end up with a new version.

**Comment by WanWizard** [comment]
The current version is in maintenance, since about 2015, by the London based company https://flexcoders.co.uk. They've been our sponsors for a long time, provide us with managed hosting  for our websites, and their developers are Fuel users from day 1.

The reason for that was very simple: we were (and still are) committed to providing long term support, as business applications tend to live a long time, and there is usually seldom money available for a rewrite in another framework that doesn't introduce significant new features. And all team members are or have been plaged with health related issues, we couldn't provide it ourselfs.

Things however are a bit on the up again, Emlyn and I recently started talking, together with the development team at FlexCoders, about a new incarnation of the framework, which will have some new design features, like routing and configuration based on an OpenAPI config, Rendering (views) will be separate from Controller code to support multi-platform output, PSR standard support, no own autoloader anymore but everything via composer, no more statics to improve testability, PHP 7 strict typing, etc...

Given the stage it is in, don't expect anything usable soon...

**Comment by rotexdegba** [comment]
Thanks for the feedback. At least I am glad that my app running on FuelPHP 1.8.1 is still running on a framework that has long term support. That works for me. I will keep an eye on the FuelPHP [twitter](https://twitter.com/fuelphp)  page for any future announcements.

Thanks again!
