### ISSUE TITLE
autoloader::static function init_class()  elseif will never be executed

### ISSUE THREAD

**Issue by hamburger123456** [fuel/core#2140]
Hi,
in the named function is on line 395 the following code.

```
               // else something went wrong somewhere, barf and exit now
		elseif ($file)
		{
			throw new \Exception('File "'.\Fuel::clean_path($file).'" does not contain class "'.$class.'"');
		}
```
this will never be reached by calling the function because there is the same if statement in line 363 and  $file will nowhere changed.

**Comment by WanWizard** [comment]
You misunderstood the code.

If `$file` contains a filename, 365 will attempt to load it. If that fails, or if the file loaded doesn't contain the class loaded,  369 will be false, so that if falls down until it reaches 395, which throws the error if a filename was given, or 399 if no filename was given.

**Comment by hamburger123456** [comment]
Indeed I did not understand the code. Thx for explanation WanWizard.
I mainly looked at the give message. The message here is, if there is no $file given: Class  is not defined. And if there is no Class the Message is: $file does not contain class. This is not allways clear.
