### ISSUE TITLE
Fieldset class - ability to inject HTML between fields

### ISSUE THREAD

**Issue by calvinfroedge** [fuel/core#251]
Need to be able to place HTML tags within form.  Otherwise it becomes necessary to use the form class and build em the old fashioned way.

**Comment by nerdsrescueme** [comment]
I need the same functionality, but the question for me is how to do so in an OO fashion. I need to put more thought into this before I really get into it. Question for you, what exactly do you need in between your fields?

**Comment by calvinfroedge** [comment]
All kinds of stuff.  For one, I may want to separate my form elements into separate fieldsets.  I may want to have help hints with images or video, or a lot of text in them.  I may want to have heading tags and salesy type messages in between fields.

**Comment by nerdsrescueme** [comment]
I think there are a number of ways we could accomplish this, but I can't think of what would be best. Perhaps we can have a way to inject code generated from the HTML class in between each item. I don't think extra methods would be the way to go (ie. \Fieldset::instance()->inject('html')) ... but perhaps each \Fieldset_Field can have a before and after attribute (array key) that can add any extra tags pertaining to that field...

But then it leads me to think that maybe some UJS would be the solution. Instead of clouding up the application, maybe that extra markup does not belong within a Fieldset... seeing how it's not directly related to the form...

Perhaps some sort of extra functionality where you could run a "filter" on the Fieldset output and have a find/replace function... ###BEFORE_CODE### (input type="text" / )###AFTER_CODE### where the "filter" could replace the placeholders with code for output...

I don't know, part of me says the extra markup doesn't belong within the form itself... then the other part says the convenience is great.

**Comment by calvinfroedge** [comment]
I like your before / after idea.  I don't think JavaScript has any place in this solution - I'm a firm believer that software should work with javascript disabled.  

I think extra markup definitely belongs in the form.  Think about all of the long forms you've ever seen - hotel reservations, job applications, products with lots of configurable options (ie computers), etc.  HTML in the right place makes the forms a lot more usable - and I suppose HTML being generated by the framework has already been approved by the core team, as a class exists just for HTML.

**Comment by Mitchell64** [comment]
I agree with being able to add more functionality to the form fields. I'm not saying this is a good way to do it, but I ended up extending the Field class and adding a new variable that I called "extras" with set and get functions. When building the form, I can add extra info to each form field such as instructions or the format of the field. Before displaying each row, I added an intermediate function to add the extra information and then display the field.

**Comment by jschreuder** [comment]
I thought about this when writing it but came down that any solution would be limiting except for the one already available: only use the field templates and build the form template custom.

```
<?php echo Form::open(); ?>
<h3>Personals</h3>
<?php echo $fieldset->field('name'); ?>
<?php echo $fieldset->field('email'); ?>
<?php echo $fieldset->field('phone'); ?>

<h3>Website details</h3>
<?php echo $fieldset->field('username'); ?>

<h4>Password</h4>
<?php echo $fieldset->field('password_1'); ?>
<?php echo $fieldset->field('password_2'); ?>
<p>We require your old password as well to allow you to change it:</p>
<?php echo $fieldset->field('password'); ?>
```
