### ISSUE TITLE
Problem with function finfo_file() not enabled

### ISSUE THREAD

**Issue by Mitchell64** [fuel/core#253]
The Upload class uses the function finfo_open() to get the mime type of uploaded files. Although PHP documentation indicates that this function is is enabled by default as of PHP 5.3.0, the PHP installation on my Linux CentOS server has it disabled by default. So, file uploads fail with a hard error. My guess is that I may not be the only one with Fileinfo not enabled.

Perhaps the code should check if the function is defined. If not, either don't check, use another type of check, or throw a warning.

**Comment by WanWizard** [comment]
This has been discussed, both internally and on iRC. 

It is the opinion of the team that if the official PHP documentation states that something is an integral part of PHP, we will regard this as such, and not test for it, nor write workarounds for it.

If we start doing that, we'll end up with double the code base because we need to test for every feature someone might have decided to exclude at compile time.

CentOS doesn't include PHP 5.3, Remi's repo provides a PHP build which excludes a lot of things, so many that's the culprit, and someone needs to inform him things have changed in 5.3.

Having said that, we might be able to do something with SplFileInfo, I'll have a look...

**Comment by WanWizard** [comment]
Nope, SplFileinfo doesn't do mime types, to it's either Fileinfo (which should be present), or mime_content_type() which has been removed as of PHP 5.3.0.

Conclusion: required, and no way to work around it. 

I've discussed this with Remi, and he says that his builds include fileinfo as part of the php-common package. So there's a solution for CentOS. I've just checked a few of my CentOS servers that run Remi's PHP stack, and they all have fileinfo available.

I consider this closed.

**Comment by Mitchell64** [comment]
Thanks for looking into this. Hopefully, my particular build is atypical. 

BTW, I just checked with my hosting company, and their reply regarding why Fileinfo is not installed is that it's disabled by default in the EasyApache configuration.

**Comment by WanWizard** [comment]
What a bunch of morons.

Easyapache is a cpanel script that compiles apache and php, and is probably not updated for PHP 5.3. Very easy to fix, if they can't even do that, maybe it's time for another hosting company?

**Comment by Mitchell64** [comment]
It's already been fixed and also updated to PHP 5.3.6. I assume it's just the default configuration. Wasn't a big deal.

**Comment by WanWizard** [comment]
Good. I wish more hosting companies would be so customer focused!
