### ISSUE TITLE
Feature: Session::set() to have a 3rd parameter as $expiration_time N seconds

### ISSUE THREAD

**Issue by huglester** [fuel/core#264]
Hello everyone,

I think it would be great, if we could sometimes set the $expiration_time value when setting the variables into the session.
In that way, our whole project would use the default config $expiration_time, but for some values we could set it up individually

It would also won't break any existing code, for example:
Session::set('demo', true, 3600); - this would set the key 'demo' which will be available for an hour

Hope you like the idea, and thanks once again for such a great product!

**Comment by WanWizard** [comment]
Sessions work with an expiration on the session cookie, which if it expires, will expire the entire session.

If you want expiration on individual session variables, most of the session drivers needs to be rewritten, because you need to store meta data (= expiry timestamp) with the value, and you'll have to add logic to deal with this when getting and setting values. 

Definately not for 1.0, I might think about it for future releases...

**Comment by WanWizard** [comment]
Scraped this idea permanently. Very difficult to implement, and will be performance impacting for those that don't need this.

As a workaround, create parallel sessions. I tend to use a storage driver for the regular session data, and a second session instance using the cookie driver for some long-lived data like a remember-me token. The first one can then expire while the second one is still working.
