### ISSUE TITLE
Feature: Cache class to have fallback

### ISSUE THREAD

**Issue by huglester** [fuel/core#267]
Hello,

I've been using cache class widely with no problems, until I wanted to restart redis server.
And here the problem begins, that you start getting exceptions all over that it can't connect to redis server.

I think it would be good idea to have smth like $fallback = array('memcached', 'file');
in that way it would try to fallback to memcached and if that fails too (probably bad day :D ) it would fallback to file...

Since I can't mark as a feature, I'm leaving Feature in the subject

If you think this won't go into the core... probably close the issue

THanks for your time and have a good day/evening :)

**Comment by WanWizard** [comment]
I have a problem with this request, as it tries to workaround the real issue, which is the configured storage backend is no longer available. If it is required for your application, it should be there. Same as with your database and webserver.

This is the real issue that needs to be fixed, and not worked around. You don't have a fallback for your database in case you decide to restart MySQL, do you?

Now, I can imagine that you get errors if the backend is unavailable, your application should catch that. But that should be over when it is restarted.

**Comment by jschreuder** [comment]
I agree with WanWizard and even if you do want it I don't think it belongs in the core. It should be easy enough to write this with an extension of the Cache class, but won't be desired behavior for (I expect by far) most users.  
Also a failing cache shouldn't crash your site, it would be a bit heavier, but your site should be able to run without cache as well (otherwise it's not really caching, just another data storage)

With 2 votes against I'm closing this.
