### ISSUE TITLE
Prefixes for DB not being applied with DB::query()

### ISSUE THREAD

**Issue by jasonlewis** [fuel/core#284]
This may be intentional, but to me it is quite annoying that the DB::query() method does not automatically prefix table names. By that I mean:

```
\DB::query('SELECT foo FROM bar')->execute();
```

If your Database_Connection object has a table prefix of **fuel_** it would not get applied to this query automatically. I've been doing it similar to this to achieve the desired result.

```
\DB::query('SELECT foo FROM :table.bar')->bind(':table.bar', \DB::expr(\DB::quote_table('bar')))->execute();
```

To me that seems a bit to long winded, and I'm unsure how easy it would be apply the quote_table() method to table names when using DB::query().

**Comment by philsturgeon** [comment]
This is intentional. Use DB::table_prefix('table_name').

While we could do some regex this is not a viable solution. Table aliases would end up getting prefixed, or database names would be prefixed when using `select * from otherdatabase.tablename` type syntax.

In short you need to use the method as we cant and wont do this auto-magically.

**Comment by jasonlewis** [comment]
Yeah okay so the method I mentioned is the solution then? I found I was required to use DB::expr() otherwise the table would be formatted as such:

```
'`prefix_tablename`'
```

It has the single quotes and the back ticks applied to it.
