### ISSUE TITLE
Request Problems

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#296]
We have been debugging problems with routes, requests and HMVC for a few weeks now. @WanWizard has been helping on some aspects. The request system needs serious consideration before Fuel v1 is released.

For example, because it does not use a stack for requests - rather just a main and previous, you cannot adequately chain HMVC requests. This is apparent when a HMVC request occurs to an invalid location and an additional 404 request is generated - wiping all trace of the original request.

The other issue is with the request system twinned with JIT rendering. Take, for example, a View object being created in a template. We use this as a way to create a recursive navigation. When the View object is rendered, it has no concept of the context in which it was created. This causes problems if HMVC requests are cascaded - i.e. a requests b, b requests c, c requests d, etc. This is because, when the template and thus the View is rendered, the current request is the original request - not the HMVC request.

@WanWizard identified this as  a critical architecture design problem that means things need a serious rethink. He will be able to provide more information about this.

For what should be such an elegant system - HMVC has provided no end of pain when trying to use it.

**Comment by jschreuder** [comment]
From a quick look through all of it I think you maybe overstating the severity of this a little bit. I'm not saying these aren't very real issues, but they don't seem that hard to fix. But please, correct me if I understood anything wrong...

**Request stack**
This seems solveable by just adding an array which keeps track of all requests created, that should allow for traversing. Though I'm not sure if a stack is the best datastructure, a tree seems more flexible and representative to me - although harder to work with. This isn't that big of a thing either way, we could implement this without breaking compatibility.

**show_404()**
We could make a dynamic method for this as well, which triggers a Request::show_404() only when the exception wasn't caught in time. That would allow you to handle it while not changing how it works currently.

**JIT rendering**
To be honest, I like this feature and it's easily worked around if you want it rendered sooner: use a controller extension with an after() method that forces your views to render.

**Comment by phil-lavin** [comment]
The stack is a fairly simple fix, I agree.

The JIT rendering is indeed a nice feature but how useful is it? The documentation suggests breaking projects up into modules and, as such, all projects will be HMVC heavy. If you must manually render anything that relies on a Request context other than the original the JIT rendering will have very limited purpose.

I'm not sure if we're the only ones doing non-basic HMVC work but I think it does need a significant amount more testing before it is released.

**Comment by jschreuder** [comment]
Actually while thinking about it I think we should do it as a tree: each Request instance should have a $parent property and a $children property, all requests created are added as children to the current active request and get that request assigned as their parent. That would automaticly build a tree with Request::main() as the root, and you could traverse requests using $request->parent() and $request->children() methods.

JIT rendering is quite usefull for views of course, so I take it you point is about JIT rendering for Requests? That actually results from the JIT rendering of Views as requests are executed manually. The point there is that it might be quite usefull to get a View object returned instead of a fully rendered View, in fact it's nice that a Request might return whatever you make it without forcing it to be a string. Thus it's not a good idea to force this to render when the Request is executed, but if you need it: that's the reason Fuel is very extendable, to allow you to change behavior like this.

As I said your points are valid but by far not as debilitating as you suggest, in fact quite easily fixed. What Fuel needs now is a first release. Your issues are issues but not bugs, and as such don't have to hold back a first release but be part of a 1.1 release. Even the 404 problem isn't a real bug, though I agree it's undesired behavior. At some points you gotta say: we're going to release, it's gotta be bug-free but it's up to the next version to move towards perfection.

**Comment by ghost** [comment]
I agree on leaving it as is, but definitely consider it for 1.1. I think a lot of the community is being held back by not having a stable release to work off (although RC3 is quite stable), we need a first version.

**Comment by jschreuder** [comment]
Guys, let's keep to the topic. I know we all want v1.0 out, that's not what's being discussed here and you should be reassured by my words on the subject. This is about some issues with the Request class that are real and need a solution, whether that solution goes into 1.0 or 1.1 will depend upon how much code needs to be changed and if it might have consequences for those on RC3.

**Comment by jschreuder** [comment]
These commits address your concerns about traversing requests and not being able to deal with HMVC requests that 404. I'm interested to know if this really solves those issues for you, and if these don't contain any new problems.

Lastly I think I've gone over the JIT parsing, and why I don't consider that a bug. Any additional comments on that?

**Comment by dhrrgn** [comment]
Regarding the JIT rendering:  This is the default but not only behavior.  As it says in the docs you can just call ->render() on a view to render it and return the string right then.  You can also force a Request to be rendered immediately by casting it as a string:

```
$foo = (string) Request::factory('admin/users/list')->execute();
```

Lets not make things bigger than they are, especially without reading the documentation thoroughly before hand.  What @jschreuder has done is good for now and will make it into 1.0, your other requests however will not.
