### ISSUE TITLE
Make loaded configs merge recursively

### ISSUE THREAD

**Issue by jschreuder** [fuel/core#298]
Replace array_merge() with new Arr::merge() method in Config::load(), will be a little bit slower but also give far better results. @wanwizard already took a quick look and turned out most of our core Configs actually have options deeper than one level, which you can't overwrite individually currently.

**Comment by dhrrgn** [comment]
Agreed this does need addressed.  We will need to look into the performance impact of this tho.  Moved to Milestone v1.1-dev.

**Comment by jschreuder** [comment]
I've been thinking about how to test this, and the problem is that it's not really possible to test this fairly. Arr::merge() will not just be slower because its not coded in C, but also because what it does is far more complex than what array_merge() does. The native function only cares about the upper level and merging 2 multi-dimensional arrays will thus take array_merge() no time at all while Arr::merge() needs to go in deep. Thus the question isn't really if it's slower, we know it is, but how much slower do we think is acceptable and what testing setup can we create to test it? I don't really have a good idea yet...

**Comment by WanWizard** [comment]
I've noticed some other issues with array_merge() as well, such as renumbering of numeric keys, which is undesired.

I've done some benchmarking, in a loop of 1000, 10 tries on my system, on a substantially large array:
- array_merge() takes 12998 µseconds
- array_merge_recursive() takes 76989 µseconds
- Arr::merge() takes 1145826 µseconds

So yes, conclusion that Arr::merge() is quite a bit slower is justified.

However, at the moment I don't see any way around it, and since it isn't called that often, I went ahead and changed the merges to use Arr::merge(). Any suggestions on improvement welcome, but at the moment, I'm with @jscheuder on this...

**Comment by jschreuder** [comment]
Wow, 8800% is pretty bad - on the other hand that is about 0.00011 per heavy config file which isn't all that terrible either. And I don't see another way either, as array_merge_recursive() sucks because it bundles values of conflicting keys into arrays.

**Comment by WanWizard** [comment]
A quick test on a real live app:
- array_merge(): Time per request: 106.683 [ms](mean, across all concurrent requests)
- Arr::merge(): Time per request: 104.461 [ms](mean, across all concurrent requests)

**Comment by jschreuder** [comment]
Has been implemented.
