### ISSUE TITLE
Allow callbacks for defaults

### ISSUE THREAD

**Issue by dhrrgn** [fuel/core#328]
We should allow callbacks for all defaults in the framework.  Here is an example of where this would be awesome:

``` php
$username = Session::get('username', function () {
    return Model_User::get_username_by_id(Session::get('user_id'));
});
```

This would allow you to execute a block of code if the value is not found.  It could simplify a lot of code (e.g. less if statements, etc.).

Thoughts?

NOTE: This is inspired by the Laravel Framework...they do this almost everywhere...it is pretty awesome.

It would be as simple as doing this anywhere we return the default:

``` php
return is_callable($default) ? call_user_func($default) : $default;
```

**Comment by nerdsrescueme** [comment]
I really like the idea of enabling closures in more areas. Seeing how one of Fuel's biggest selling points is that it actually uses PHP5.3 to its fullest... it would make sense with the philosophy as well.

EDIT: Wow, I really like Lavarel's use of closures in the Config class... That really opens up a lot of opportunities for code refactoring and removing single use methods from a lot of areas of my work... 

For instance, they use it in the Auth class... then they call Config::get('auth.by_username', null) and the Config class then performs what's in the closure instead of needing to do a ton of calls within the class itself...

Actually this will be VERY useful for modules as well. I can think of several places to use this inside of my Blog Module, and it solves the problem of having a modular reusable model (like users for Authentication).

I really hope this makes the cut.

**Comment by jschreuder** [comment]
Great idea, maybe allow this for setters as well for the value?

**Comment by dhrrgn** [comment]
Ya, that would be awesome too (the setters).

@nerdrescueme It isn't a horrible idea, but kind of defeats the purpose of a configuration file IMO.

**Comment by nerdsrescueme** [comment]
Well perhaps, but it fits very well for my purposes... So if it doesn't make it in I will just extend the core class and release it for those who would like to use it :)

**Comment by dhrrgn** [comment]
This is now complete here: https://github.com/fuel/core/commit/1f9b5faf20f49c89a571bd6081f9e57b8705275f

I also allowed for any callable in any config option as well. (@nerdsrescueme)

**Comment by nerdsrescueme** [comment]
I think I love you.

**Comment by philsturgeon** [comment]
Coming in on this one a little late, but I've been up a mountain for most of the last two days.

Is this just code for the sake of code?

```
$username = Session::get('username', function () {
    return Model_User::get_username_by_id(Session::get('user_id'));
});
```

Could that not just be:

```
$username = Session::get('username') ?: function () {
    return Model_User::get_username_by_id(Session::get('user_id'));
});
```

**Comment by dhrrgn** [comment]
No, it is rather useful.  The example given was not the best one, as it was super simple.  Closures can also be used on setters and as config values now as well.  Also, the overhead this adds is so negligible, you would have to use a callback over 200,000 times just to add 1 second to the execution time.
