### ISSUE TITLE
New 404 Exception stuff

### ISSUE THREAD

**Issue by tarnfeld** [fuel/core#366]
Hey,

I guess this isn't really an issue, more of a feature change request. I have just updated my index file with this new 404 exception stuff... and I plan to extend the request class to remove this. Im my opinion, this kind of 404 catching functionality should be all kept inside the router/dispatcher and nothing to do with my index file.

Personally I think the index.php should be so far removed from the framework that all it does is setup highly important options the framework relies on, such as the paths, error reporting and calling the first dispatch loop. This kind of 404 handling should be in the request/router (or whatever the relevant class would be).

Also, I don't think its particularly good to just replace stuff in someones output and if they don't want it just comment it out, (https://github.com/fuel/fuel/blob/develop/public/index.php#L60) this kind of functionality should be optional, and you can get it out yourself in whatever view you wish by calling `Profiler::app_total()`

Hope your not planning on keeping it like this :-) Looking forward to see if this changes at all.

Thanks,

PS. Trying not to come across too rude, but just wanted to voice my opinions on these recent changes... would love for an explanation on why you may have made these changes? :)

**Comment by philsturgeon** [comment]
Seconded. Really not a fan of this!

**Comment by tarnfeld** [comment]
Glad you agree, I just love how fuel works and think is it totally in the wrong direction!

**Comment by dhrrgn** [comment]
The exceptions stay.  If you don't catch the exception it will do what you would expect.  Just simply remove the try catch block.

As for the profiler thing.  READ THE COMMENTS.  It says if you don't want Ut to comment it out.  These are the defaults, it don't work for every app, sometimes you need to change things.

A 404 is an error.  How do you properly represent errors in code?  Exceptions, that's how.

And yes, you came off as a dick.

**Comment by dhrrgn** [comment]
Regarding the index.php:  It is meant to control how the request is made, which is why the 404 handling is there.  Like u said tho: if you remove the try catch block, it will still respect your 404 route (through the new handle() method that gets auto-called on Exceptions now,

**Comment by jschreuder** [comment]
To clarify further and close this: @dhorrigan and I talked this through and didn't decide this on a whim.

What we did is the following: 404's are now fully thrown instead of exited and no longer have any kind of hacky trick to make them end up in a 404 location. In the core this would mean it ends up just calling the 404 view and exiting when the Request404Exception isn't caught. We did however at one point decide to support a magic `_404_` route which would be where the Request ends up when a 404 happens. To keep supporting this but no longer make it part of the core we moved this to the public/index.php where it catches a Request404Exception when not caught in the app, tries a `_404_` route and only then might it rethrow to the default 404 view.

Thus that code is in the public/index.php for backwards compatibility and becasue many people will use it like that probably, we don't consider it part of the core any longer though.

**Comment by tarnfeld** [comment]
I see, thanks for explaining. Makes a little more sense, so if it's for backwards comparability what is the new official way of dealing with these errors?

**Comment by jschreuder** [comment]
Any you like. The "official default" is still the `_404_` route, but you can change that to whatever you like. For example by extending the Request404Exception class and overwriting the handle() method to have it work however you like.

**Comment by tarnfeld** [comment]
Interesting, well thanks again for clearing all this up.
