### ISSUE TITLE
[v2.0] Better environment handling

### ISSUE THREAD

**Issue by jschreuder** [fuel/core#394]
Currently environment is handled in a way that works, but I'm not really satisfied with it. A couple of gripes:
- All db config is done in the same file, thus the db config files in my repo and on my server conflict
- Some decisions in the Error class are based on Fuel's native environment constants - these should be per environment settings, not hardcoded constants
- I can change the environment based on a .htaccess, but most things (like logging, caching) can't be overwritten per environment

I think this should be redone in a way for v2.0 that would allow the dev to use different config files ("overwrites") based on the environment, sometimes taking those from app/config (the defaults) and sometimes loading environment specific files from another location (or by filename suffix, or in a subdir, etc..)

**Comment by tomschlick** [comment]
I like the subdirectory way of doing this because its the cleanest & most backwards compatible way. Basically you would have app/config/db.php and then you would have something like app/config/production/db.php.

the production db.php would have a small segment of the array that the regular one has and would be merged over it. you would have folders for each environment (production, test, and development) only if you needed to. Otherwise it wouldn't effect you.

**Comment by dhrrgn** [comment]
Yes, it definitely needs addressed.  Someone (@tarnfeld I think) has a pretty good way that they handled it where the environment configs merged down into the global config so that you could override any config option per-environment.

I also agree that we may need to change the way we handle the environment constants.

**Comment by tarnfeld** [comment]
I'm going to work on a more general environment based config switching process tonight, will create a branch on my fork (tarnfeld/core) and you guys can take a look and see what you think.

**Comment by jschreuder** [comment]
Important first step was just done by @tarnfeld in #564 by making the configs environment sensitive.

**Comment by frankdejonge** [comment]
Closing this as this is already done in 2.0, right @jschreuder?

**Comment by jschreuder** [comment]
Completely rewritten with the above in mind.
