### ISSUE TITLE
Binary data problem, maybe?

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#404]
I have this function:

``` php
public static function get_by_ip($ip) {
    $ipesc = \DB::escape($ip);
    $query = \DB::query("
        SELECT * FROM GeoTargeting.geo_target_data
        WHERE CONTAINS(line, GeomFromWKB(POINT(0,INET_ATON({$ipesc}))))
        LIMIT 1
    ")->as_object('\GeoLocation\Model_IP')->execute();

    if ($query->count()) {
        var_dump($query->current());
    }
}
```

This causes this error:

Exception [ Error ]: Could not execute GeoLocation\Model_IP::__construct()

Changing it to this fixes it:

``` php
public static function get_by_ip($ip) {
    $ipesc = \DB::escape($ip);
    $query = \DB::query("
        SELECT start_ip_text, end_ip_text, start_ip_numeric, end_ip_numeric, country_code, country_name FROM GeoTargeting.geo_target_data
        WHERE CONTAINS(line, GeomFromWKB(POINT(0,INET_ATON({$ipesc}))))
        LIMIT 1
    ")->as_object('\GeoLocation\Model_IP')->execute();

    if ($query->count()) {
        var_dump($query->current());
    }
}
```

The difference is that I manually select all fields except a field named `line`. `line` is a field of type linestring and dumping the executed query as an array pumps out a bunch of binary data.

I am thinking that this does not like binary data going into the construct.

Thanks in advance :)

**Comment by jschreuder** [comment]
Not really sure if `__construct()` cares, does it work with `GeoLocation\Model_IP::find(...)`? In that case it's not the constructor that fails but something else...

**Comment by phil-lavin** [comment]
I had this issue again the other day when using as_object with a select \* and entirely non-crazy data. find() works on that model.

**Comment by jschreuder** [comment]
The problem is that the Orm\Model was never intended to work with this type of hydration. All the normal checks and preventative measures (for example to prevent the same row from instantiating 2 objects) don't happen. And even though @FrenkyNet added support for it I don't intend to fully debug or sacrifice anything to support it, partially because I expect (haven't tested it though) that this type of hydration will be slower (it needs `__set()` to work, which is notoriously slow).

**Comment by jschreuder** [comment]
Without any more info this can't be resolved, open a new issue with full description if you find out why this happened.

**Comment by phil-lavin** [comment]
You haven't asked for any more info... What do you need to know?

**Comment by jschreuder** [comment]
Your original hypothesis of what was wrong proved false and you didn't have a new idea of what went wrong. And as I said I care little about this type of hydration as it was never my intention to work like this. So I'm not going to test until I get the same error. If you figure out what the problem is I'll help you fix it but until that time I don't consider this an issue.
