### ISSUE TITLE
Allow manual input data for Fieldset::repopulate()

### ISSUE THREAD

**Issue by kbanman** [fuel/core#501]
The input parameter of repopulate() is being deprecated for 1.1, but I believe it's meaning just needs to be changed:

`$fieldset->repopulate()` works fine if the changed values are sitting nicely in POST, but I have already run into the case where the input values that have changed and need to be validated aren't in POST, and therefore I need a way of passing those values into the fieldset manually.

Why not make Fieldset::repopulate() be essentially `repopulate($input = Input::post())`? (Be able to specify a source for repopulation, but default to the Input).

If this suits everyone, I'd be happy to send a pull.

**Comment by jschreuder** [comment]
The above commit addresses your point about `repopulate($input = Input::post())` but adds support for all HTTP methods instead of the old GET/POST support.

You also want manual repopulate() input, and I'm assuming you know about `Fieldset::populate()`. My problem is that it's not what repopulate is actually meant for, repopulate is meant as just what it's described as: to repopulate based on the input. I think that what you want is easily done using `$fieldset->populate($original_object)->populate($manual_input);` - otherwise the methods overlap too much with effective functionality.
