### ISSUE TITLE
ErrorException [ Error ]: include() [function.include]: Cannot redeclare class fuel\core\event

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#542]
Just upgraded to the latest core and I'm now getting this. I have put some debug in the autoloader and it tries to include fuel/core/classes/view.php just before it breaks. I'm a tad confused by this.

**Comment by phil-lavin** [comment]
Seemingly without me doing anything, that error has now been replaced with:

ErrorException [ Error ]: include() [function.include]: Cannot redeclare class fuel\core\crypt

**Comment by phil-lavin** [comment]
This seems to be caused by this call in alias_to_namespace:

class_alias($class, $root_class);

**Comment by phil-lavin** [comment]
xdebug error: http://imageupload.org/?d=84E3EF131

**Comment by phil-lavin** [comment]
It was apparently APC. Why do we use this shite...?

Sorry to bother :(

**Comment by jschreuder** [comment]
@phil-lavin could you please do some decent checking before creating an issue next time? I think this is the 4th time this month you created an issue and closed it a while later because it turned out to be a mistake of your own. Our issue tracker is not here for you to voice your frustrations with your own mistakes.

Verify if it's an actual bug first, especially after a new pull.
