### ISSUE TITLE
Feature request - Allow Fieldset::add() to take Fieldset_Field object as argument

### ISSUE THREAD

**Issue by Savageman** [fuel/core#547]
The title is self-explanatory.

It's already possible to use an array, but a Fieldset_Field object would be nice.

The reason for this is I'm creating some custom Fieldset_Field but I need to extends the Fieldset class (either by extending the native add() or by creating a new method to add my field) to be able to use them. Kind of a shame.

**Comment by jschreuder** [comment]
This was requested and denied earlier in #503, I'll just repost what I said then:

> Each field can only belong to one Fieldset, that's one of the basic assumptions made in the whole thing and not something I intend to break. While I don't have anything against allowing you to forge your own Fieldset_Field instances which you could input into `Fieldset::add()` I didn't see any use for it as that method is practically already the factory/forge method for Fieldset_Field no reason to add complexity.

**Comment by Savageman** [comment]
I didn't check for other similar feature request before adding this one. Sorry for that!

Not sure if my problem should be explained here or in the forum, but i'll make it here because that's where the discussion initiated.

I want to create custom Fieldset_Field for inputs.
The most basic one would be a simple text (no input tag at all) to insert in the middle of the form (to replace a readonly field with text).
Another use case is a custom date input which would displays 3 select to pick the year/month/day. The set_value() would dispatch the appropriate part of the dates to the appropriate input.

How could I achieve this?

**Comment by jschreuder** [comment]
I'm open to allowing add() to accept Fieldset_Field instances, but only through a pull-request and it still must make sure that each field belongs to a fieldset and only one fieldset.

Don't think there's a better way to achieve the multi-fields template except for giving it a template of its own with the actual value in a hidden field and using JS to fill out the fields using the value in the hidden field.

Adding HTML this way is something I've always been opposed to as forms are generated mostly in models or controllers, and there shouldn't be any markup in models or controllers. If you want such customized output you should generate each field individually in your view instead of the auto-form generation.

``` php
<?php

$form = Form::instance();

echo $form; // auto generate the full form

// vs

echo $form->field('username');

echo '<p>some html</p>';

echo $form->field('password');
```
