### ISSUE TITLE
Session previous_id is a threat

### ISSUE THREAD

**Issue by arbme** [fuel/core#559]
I have been playing with the session db class and have come across some interesting findings.

I found that if I call rotate() (had to edit to make work for testing) to create a new session_id and encoded cookie. If I then use the previous encoded cookie data, the session class passes it, so gaining access through session hijacking is possible. 

Most interestingly both previous_id and session_id are reset in the db to the previous_id, thus logging out the user who logged in first who happens to be the owner of the account. The fact that the hacker can simple reuse the hijacked session over and over and when rotate() is called after x amount of time, his cookie is refreshed and continue doing damage.

I no pro on security, hell im no pro at php but seem to me having previous_id like this is a security hole and I don't undertsand fully why it is there.

E.g.
1. Owner visits site logs in and gets cookie[1].
2. User gets cookie[1] hijacked and then rotate() is called after x amount of time, new session_id and cookie[2] are given to owner only.
3. (a) Hacker uses cookie[1], it passes and hacker has access to user's account. Session sets in db both session_id/previous_id to the id sent in cookie[1] which is the previous_id.
4. Owner navigates the site and is logged out due to his session id not being in the db anymore.
5. Hacker continues browsing the users account.
6. Owner logs in again.
7. Aslong as the hacker keeps using cookie[1] before the rotate() is called he will remain in control. Go to step 1.

Hope this helps and would love hear your opinions and to help furthur.

Great work so far guys!

**Comment by WanWizard** [comment]
Rotating the session id isn't the only security measure. Session cookies are also locked down using the IP address and the browsers user agent string. The hacker must not only hijack the cookie, but also be able to spoof the IP address.

As to the security hole, keeping the previous cookie only means a given session cookie is valid for two times the session rotation time. By default, this is set to 300 seconds, making a cookie valid for max. 600 seconds. If you don't like that, lower the rotation time.

This mechanism is there to facilitate website that use lots of ajax calls. When you have a short rotation time, you can run into the situation that one ajax call triggers the rotation, while a second call still uses the old session cookie, since the browser hasn't been updated with the new cookie yet. 

The shorter the time the cookie is valid (i.e. the shorter your rotation time), the more chance you have of running into this issue.

What is a good and secure (enough) rotation time depends on your application, it's you who has to decide.

From a security point of view, I am a lot more worried about people using 'remember me' cookies for their applications, allowing the user to be logged in without supplying credentials. It is even more difficult to secure a cookie like that, so from a hackers point of view, I would try to steal that cookie, since due to it's nature it can not expire.

**Comment by arbme** [comment]
Thanks for the detailed replay to better get my head around why we have previous_id and what its used for. I agree with you completely about the 'remember me' or persistent login cookies. I think its the work of the devil as its for lazy people.

I still think there is a error with the code when the previous_id is handled.

E.g.
1. First ajax call triggers rotate() and is sent new session cookie.
2. Second ajax call sends old session cookie, session_id in database is overwritten with previous_id (session_id/previous_id have the same value).
3. Third ajax call sends new session cookie, this fails as new session_id can't be found in the database.

This is the quick fix I have come up with.

Session_Db
Line 104

old...

// record found?
if ($this->record->count())
{
    $payload = $this->_unserialize($this->record->get('payload'));
}
else
{
    // cookie present, but session record missing. force creation of a new session
    $this->read(true);
    return;
}

new...

// record found?
if ($this->record->count())
{
    // previous id used, correctly set session id so it wont be overwritten with previous id.
        $this->keys['session_id'] = $this->record->get('session_id');
    $payload = $this->_unserialize($this->record->get('payload'));
}
else
{
    // cookie present, but session record missing. force creation of a new session
    $this->read(true);
    return;
}

I still think its a hole but less of a hole now. 

Would a better way be to check like this:
1. Ajax sends session cookie. If previous_id is sent, send a message like 'previous_id_refresh' so the ajax call knows its failed due to an old session id and not a wrong session id.
2. Ajax trys again and could have limit to the amount of times it trys, after x amount of trys reload the page.

I know this could cause slow downs but not major ones and would leave less of a hole to crawl through by using old session cookies.

Let me know what you think.

**Comment by WanWizard** [comment]
The result of an ajax call will update the browsers cookie cache.

So in your example, if the third ajax call starts after the first one is finished, it will send the new session id, If not, it will send the old session id. Both will be found.

It only goes wrong when you have an ajax call that takes longer to process than the session id rotation time, because you can then have two rotations, in which case you lose the first session id.

It is a race condition that can't be completely avoided due to the async nature of ajax calls. keeping more session id's is a better solution then extending the rotation time, because the ajax call sequence could be fired when the session id is about to expire.

This mechanism has been tested extensively, with a controller that fired random concurrent requests over a 24 hour period.
