### ISSUE TITLE
Cache File driver doesn't do garbage collection

### ISSUE THREAD

**Issue by WanWizard** [fuel/core#613]
Which if you use it a lot, can quicky fill up your cache directory with files that will maybe never be accessed, and therefore never removed from disk. Not really a bug, but very annoying none the less.

We should add some form of garbage collection to the driver to prevent this from happening.

**Comment by jschreuder** [comment]
I have thought about this a few times, but the problem is that especially for big systems where this is usefull this will take massive overhead. Even if you do this using a once in a while probability, the overhead of checking many files will take a lot of time as file operations are pretty expensive (though still less expensive than DB obviously).

You'll also have added overhead probably because you need some way to index the caches, indexing those in a file could get expensive quickly on the bigger systems for which this might be usefull.

It might be possible but it shouldn't sacrifice speed, if the consequence of this would be a potentially heavy series of checks and fileloads on bigger systems it's just not worth it. If that's the case it's an acceptable limitation of the driver IMO, and you just have to use one of the others if you need the garbage collection.

**Comment by WanWizard** [comment]
I was thinking about using a shutdown event to do the processing after the output has been send. 

I haven't thought of a clever way to detect what could be deleted. I discarded the option of maintaining an index, as that would slow down all caching operations (by adding a read and a write to each one) and use additional memory. On the other hand, going through all files and reading each one to check the header isn't viable either. An option maybe is to split the cache file into a separate meta file (containing the header) and payload (with the data). But that will also increase the number of I/O's...

**Comment by WanWizard** [comment]
grrr.. Don't you hate that "comment and close" button... :(

**Comment by jschreuder** [comment]
@WanWizard tbh I still don't think it's doable and should be considered a known limitation. Only worthwhile type of GC I can think off would be to add a method that deletes all files with a modified date older than a given time-limit - that should be doable, though still only through a cron-job and not automated during read-write as it would still slow down the process too much.

**Comment by WanWizard** [comment]
I agree that it's a daunting task.

You could add such a method to the shutdown event, then it will be processed after the page has been rendered and send to the client, causing virtually no impact.

Maybe document this, and/or document how to write a task that can be called through oil to do this?

**Comment by jschreuder** [comment]
> You could add such a method to the shutdown event, then it will be processed after the page has been rendered and send to the client, causing virtually no impact.

Downside of that would be that it would still show the page as loading.

> Maybe document this, and/or document how to write a task that can be called through oil to do this?

That would be my preference: document some notes about GC in all systems, with limitations and such and why it's a limitation. And that could include recomended solutions like the oil/cron-job solution (probably with included task in the core).

**Comment by WanWizard** [comment]
> Downside of that would be that it would still show the page as loading.

True.

So who's going to document it? ;)

**Comment by WanWizard** [comment]
Done here: https://github.com/fuel/docs/commit/78a9663c8709ecadf6487fef07e14d2f59d7889e
