### ISSUE TITLE
Key uploaded files in Upload class by field name

### ISSUE THREAD

**Issue by peter-fritchley** [fuel/core#647]
Would it be possible to change the upload class so that files are keyed by field name? at the moment they are numerically keyed which makes it difficult to find the file you're looking for.

**Comment by andrewwheal** [comment]
This would be really useful rather than having to retrieve file information from Upload::get_files() based on the form field's position (when you have multiple file uploads)

**Comment by WanWizard** [comment]
I'll put it on the list, but as we're in feature freeze at the moment, it's not going to be for v1.1.

I do have a question for you both though: which filename? During processing there are many rules that can cause the filename to change. If you want to be able to get the data by filename, that presumes you know the name in your code?

**Comment by andrewwheal** [comment]
@WanWizard, we were on about field name not file name, so the name attribute of the `<input type="file">` form field.

This is already in the array of data returned by \Upload::get_files() it would just be useful to also have it keyed by this so that we don't always have to loop through all files checking the file information.

**Comment by WanWizard** [comment]
Ah, ok, sorry. Starting to see double after a week of 15 hours/day coding... ;)
