### ISSUE TITLE
Routing HttpServerErrorException

### ISSUE THREAD

**Issue by zoe-edwards** [fuel/core#700]
I’m not sure `HttpServerErrorException` behaves the same way `HttpNotFoundException` does.

Here’s my `routes.php`

```
return array(
    '_root_'  => 'public/index',
    '_404_'   => 'public/404',
    '_500_'   => 'public/500',
);
```

Here’s that part of Controller_Public

```
    public function action_404()
    {
        $data['msg'] = 'Page not found';
        $this->template->section = View::forge('global/error', $data);
    }

    public function action_500()
    {
        $data['msg'] = 'Server error';
        $this->template->section = View::forge('global/error', $data);
    }
```

Fuel always returns its default error page, when calling `HttpServerErrorException`.

**Comment by jschreuder** [comment]
That is because support for the `_404_` route isn't actually part of the core. It's supported [through the index.php front controller](https://github.com/fuel/fuel/blob/1.1/master/public/index.php#L40). 

What is part of the core is that there are 404 & 500 views loaded when things go wrong, check out [httpexception.php](https://github.com/fuel/core/blob/1.1/develop/classes/httpexception.php).

**Comment by zoe-edwards** [comment]
So if I wanted my own 500 error pages, what would be the best way to write that in?

**Comment by jschreuder** [comment]
- Extend HttpServerErrorException in your app and overwrite the handle() method to execute a request based on a `_500_` route.
- Add a `catch (HttpServerErrorException $e)` to the index.php to check for the 500 exception and handle that like the 404 exception.

**Comment by zoe-edwards** [comment]
Dank u, I’ll give them a shot!
