### ISSUE TITLE
Controller_Template is (only) using the deprecated method $this->response

### ISSUE THREAD

**Issue by ipalaus** [fuel/core#739]
Hello,

As far as I know and chatted on irc with @WanWizard, Controller_Template uses `$this->response` that is deprecated but it doesn't offers an a alternative.

It needs to be updated.

Thanks

**Comment by jschreuder** [comment]
It works like that mostly for backwards compatibility, once the `$this->response` property is fully removed it will be generating a new Response object (instead of using the existing one) when none is returned by the controller method.

[edited]
Otherwise we'd have to check whether the `$this->response` was modified and use it when it was but generate a new one when it wasn't (because it's deprecated, not removed). That would be such a mess that this is better for now.

**Comment by WanWizard** [comment]
I think this issue is now that all controllers extending controller_template generate tons of deprecated log messages...

If the code is deprecated, core code should no longer use it.

**Comment by jschreuder** [comment]
I don't think so? The after method returns an actual Response object thus the deprecation warning shouldn't be generated...

**Comment by WanWizard** [comment]
I haven't looked at the code itself. Could it be an issue of outdated docs (which still say you should use $this->response->body)?

Ipalaus is online in IRC, I'll ask...

**Comment by jschreuder** [comment]
Also IDE's will mark the property as deprecated when they use docblock inspections. But that's indeed part of it, it should show how to return a new response object. Will you update the docs or shall I?

**Comment by WanWizard** [comment]
I'll try to find some time later, busy now...
