### ISSUE TITLE
Allow multiple paths per type in Asset::$_folders

### ISSUE THREAD

**Issue by kloy** [fuel/core#741]
Currently only a single asset directory per asset type is supported in the Asset class. It would be ideal to support multiple directories per asset type. For example, for an asset type of css, directories of css, stylesheets, styles would be searched, not just css. 

Reasoning for this is when including third party code, different naming conventions for directories containing asset types are frequently used. Ideally one could easily include third party code without changing it to match Fuel's conventions. 

Implementing this feature could include allowing asset.php config settings asset.css_dir, asset.js_dir, and asset.img_dir to accept an array of strings as well as a string.

**Comment by WanWizard** [comment]
@FrenkyNet,

Could you have a look at this one, and see if it can be incorporated when the Asset class is converted from static to dynamic?

**Comment by kloy** [comment]
I have extended Asset for my own library and have added this feature to it. The code can be seen at https://github.com/keith-loy/fuel-jammit/commit/cd03e585e97c1f8652a85926f1230f7e80787781

**Comment by aranw** [comment]
Rather than setting a config is it not possible to make it automatically determine the folder based on the method? 

Example
`Asset::css` would work out to be the path `asset/css`
`Asset::js` would work out to be the path `asset/js`

Now how you make the element am not sure? 

Perhaps instead of making a html element a path is returned? 

Especially considering theres a Html class?

Edit: Although thinking about it that is exactly what the Uri class does... Hmmmm

**Comment by frankdejonge** [comment]
Good suggestion, I'll incorporate this.
/cc @WanWizard
