### ISSUE TITLE
Route matching is case-sensitive

### ISSUE THREAD

**Issue by WanWizard** [fuel/core#783]
Meaning a URL like /THIS/THAT doesn't match a route like 'this/that'

**Comment by alexwhitman** [comment]
This should be optional, maybe per route. Personally I'd want some routes to be case sensitive.

**Comment by WanWizard** [comment]
Point. I'll make it a feature request, rather then a bug report.

**Comment by aranw** [comment]
This should be optional but I can never see a use case where /THAT routes to a different place to /that. 

It's would be very confusing and misleading to the user.

**Comment by WanWizard** [comment]
@jschreuder, any comments?

I agree that by default URI routing should not be case sensitive. Technically changing this breaks BC, but for me this is so logical I could live with that.

Case sensitive routing should be the exception, ideally on a per-route basis. But I haven't found a decent way of configuring it without making it very complex.

**Comment by jschreuder** [comment]
First the principle:  
I disagree, no 2 urls should route to the same output - if only for SEO purposes. And while I would consider it incredibly bad practice to route differently based on casing, they're still not the same URL. The only exception I would make to this rule is that both a URL ending on a forward slash and one lacking it should route to the same page. Best thing is to redirect the URL which has wrong casing to a URL with the right casing.

But there's practice:  
The problem is that our current default routing to controllers is not case sensitive and that creates inconsistency. (this problem endures in 2.0 btw)

The solution:  
I have no clue at this point. I hold to the principle I outlined above, but I would say consistency is more important in the 1.x branch in the end (which is to say that it might still be changed for 2.0).

**Comment by WanWizard** [comment]
So, to summarize: to deal with this issue you'll have to define all your routes twice (and worst-case in any combination of case)?

I understand the principle, but I think this is something that can not be explained to users, and is very troublesome to catch in your application at the moment.

If routing has to stay case sensitive, I would suggest a config setting so this behaviour can be altered.

**Comment by jschreuder** [comment]
I'd agree with a config setting which may be altered, though it should default to current behavior to keep BC in the 1.x branch. And this needs to be solved more consistently for 2.0, I've added it to my todo list.

**Comment by WanWizard** [comment]
Ok. I'll deal with the 1.x setting.
