### ISSUE TITLE
Migrations do not support environments

### ISSUE THREAD

**Issue by kenjis** [fuel/core#901]
Current Migrations only updates "core/config/migrations.php" or "app/config/migrations.php" and does not support Environments.

But developers may use one installation as both development and test environments.

See: http://fuelphp.com/forums/topics/view/8566

**Comment by rob-mccann** [comment]
Do you mean this:

`php oil r migrate --env=production` ?

**Comment by WanWizard** [comment]
No, the problem is that the state of the migration is written to the config file app/config/migrations.php. Which means your application can only have one state.

If you want to support multiple environments within a single application installation, this file needs to be in the environment folder, not in the main folder.

**Comment by kenjis** [comment]
And `env FUEL_ENV test php oil r migrate` reads "config/test/migrations.php", but writes the state to "config/migrations.php"

**Comment by kenjis** [comment]
fixed https://github.com/fuel/core/commit/3c92f7c975807afb6065901fb8b48fa269c13cd9

**Comment by WanWizard** [comment]
Indeed. Forgot to close this one.
