### ISSUE TITLE
Lang::load causes unexpected results due to Arr::merge handling arrays with integers as keys.

### ISSUE THREAD

**Issue by chadhutchins** [fuel/core#960]
As documented in the source code, it does clearly state "Numeric keys that don't conflict aren't changed, only when a numeric key already exists is the value added using array_push()", but I'm trying to figure out why?

I ran into the issue because I had an array in my lang file that I use for dropdown population, something like:

``` php
<?php
return array(
  'numbers' => array(
    '0' => 'zero',
    '1' => 'one',
    '2' => 'two'
  )
);
```

Say you load that config file (intentionally or not) 3 times, Arr::merge does its thing handling the integer keys. And it turns into:

``` php
<?php
return array(
  'numbers' => array(
    0 => 'zero',
    1 => 'one',
    2 => 'two'
    3 => 'zero',
    4 => 'one',
    5 => 'two'
    6 => 'zero',
    7 => 'one',
    8 => 'two'
  )
);
```

This obviously wouldn't work out too well if you then try to put this array into a dropdown as it has 9 items instead of the 3 it's suppose to have.

I'm sure there was some use case at some point that drove this implementation decision. I can fix the issue either way, just want to make sure I implement what needs to be implemented. 

So should Arr::merge not handle integer keys like this? Or should Lang::load() not use Arr::merge when re-loading lang files?

Thanks!

**Comment by ghost** [comment]
<code>
$array1 = array("zero" => "0", "one" => "1", "two" => "2");
$array2 = array("zero" => "0", "one" => "1", "two" => "2");
$result = array_merge($array1, $array2);
print_r($result);
</code>
Outputs: Array ( [zero] => 0 [one] => 1 [two] => 2 )

<code>
$array1 = array("0" => "zero", "1" => "one", "2" => "two");
$array2 = array("0" => "zero", "1" => "one", "2" => "two");
$result = array_merge($array1, $array2);
print_r($result);
</code>
Outputs: Array ( [0] => zero [1] => one [2] => two [3] => zero [4] => one [5] => two )

I could go into the why, but suffices to say sometimes you need to update an old array with new values (associative), sometimes you just need to tack an array on to the end (numeric).

Anyhow, to get the result you seem to want, you just need to flip your keys and values. Then, if you need you can just array flip before you use it, or rewrite the other part to use keys instead of values and vice versa.

**Comment by chadhutchins** [comment]
@element13 I appreciate the response, but that's not exactly the issue at hand. I'm able to get around the issue that I've posted about, but my question is more around should the framework work the way that is does today.

From the original post: "So should Arr::merge not handle integer keys like this? Or should Lang::load() not use Arr::merge when re-loading lang files?"

In the use case of the framework, If I'm loading language files, the framework shouldn't handle the merge like you describe above as it doesn't return results as a user of the framework would expect.

**Comment by kenjis** [comment]
In PHP, `$a['0']` and `$a[0]` are the same.

(added)
This could be the result you want:

``` php
  'numbers' => array(
    '00' => 'zero',
    '01' => 'one',
    '02' => 'two'
  )
```

**Comment by chadhutchins** [comment]
@kenjis I appreciate the response. What you say is true, although I'm not looking for a workaround to get my one use case working. I've already done that. 

My question is about what's best for the framework. Should Arr::merge not handle integer keys like this? Or should Lang::load() not use Arr::merge when re-loading lang files?

**Comment by WanWizard** [comment]
Both the Lang and the Config class have a parameter called `$overwrite`, which allows you to switch between `Arr::merge()` (`false` and the default behaviour) and `arr_merge()`.

So the requested behaviour is already supported by the framework, if you don't want a recursive merge, use `true` for the $overwrite value.

**Comment by chadhutchins** [comment]
You're right @WanWizard, thanks. I'm not on the latest version that has the 4th param. Thanks for the help!
