### ISSUE TITLE
[Suggestion] Make ViewModel behaves consistently with the rest of the framework

### ISSUE THREAD

**Issue by Savageman** [fuel/core#990]
ViewModel doesn't get the same syntax and usage than the other features.

I'm thinking about:

``` php
<?php
Config::load('module::test');
View::forge('module::test');
Lang::load('module::test');
// but
ViewModel::forge('Namespace\View_Test');
// why not
ViewModel::forge('module::test'); // ?
```

**Comment by jschreuder** [comment]
Because the ViewModel is loading classes where Config, View & Lang are loading files.

**Comment by Savageman** [comment]
I feel it's not intuitive.
A class is just a file anyway, why does it have to be so much more complicated?

If it's a class, it would be more logical to use a class syntax then?

``` php
<?php
Namespace\View_Test::forge();
```

**Comment by jschreuder** [comment]
It's different because it uses the autoloader, it won't care where the class is coming from just as long as the Autoloader can find it. It allows for a shorter input but it will also accept the full classname. This has far different constraints and to mangle it into a false equivalency will only lead to more confusion.

**Comment by Savageman** [comment]
So the unique recommanded solution is to use this?

``` php
<?php
ViewModel::forge('Namespace\View_Test');
```

Not slick like the rest of the framework is (in my opinion).
